<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="de" xml:lang="de"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.36">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>5&nbsp; Entscheidungsbäume – Machine Learning verstehen statt nur anwenden</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./06_ensemble.html" rel="next">
<link href="./04_pipeline.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-845c23b38eaddc0f92fda52bfe77a8c8.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-8a682e290ec1fb13ec9c90c2171c650f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "Keine Treffer",
    "search-matching-documents-text": "Treffer",
    "search-copy-link-title": "Link in die Suche kopieren",
    "search-hide-matches-text": "Zusätzliche Treffer verbergen",
    "search-more-match-text": "weitere Treffer in diesem Dokument",
    "search-more-matches-text": "weitere Treffer in diesem Dokument",
    "search-clear-button-title": "Zurücksetzen",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Abbrechen",
    "search-submit-button-title": "Abschicken",
    "search-label": "Suchen"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./classical.html">Klassisches Machine Learning</a></li><li class="breadcrumb-item"><a href="./05_tree.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Entscheidungsbäume</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Seitenleiste umschalten" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Suchen" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Machine Learning verstehen statt nur anwenden</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Suchen"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Über das Buch</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Einführung</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./classical.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Klassisches Machine Learning</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./02_linreg.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Lineare Regression</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./03_linclass.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Lineare Klassifikation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./04_pipeline.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Hyperparameter Tuning und Evaluation</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./05_tree.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Entscheidungsbäume</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./06_ensemble.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Ensembles</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./07_svm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Support Vector Machines</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./deep.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Deep Learning</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./08_ann.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Artificial Neural Networks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./09_cnn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Convolutional Neural Networks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./10_rnn.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Recurrent Neural Networks</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11_transformer.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Transformers</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Quellenverzeichnis</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Anhang</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Abschnitt umschalten">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./math.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Mathe- und Statistik-Grundlagen</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./programming.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">R und Python</span></span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Inhaltsverzeichnis</h2>
   
  <ul>
  <li><a href="#regressionsbäume" id="toc-regressionsbäume" class="nav-link active" data-scroll-target="#regressionsbäume"><span class="header-section-number">5.1</span> Regressionsbäume</a>
  <ul class="collapse">
  <li><a href="#anatomie-eines-entscheidungsbaums" id="toc-anatomie-eines-entscheidungsbaums" class="nav-link" data-scroll-target="#anatomie-eines-entscheidungsbaums"><span class="header-section-number">5.1.1</span> Anatomie eines Entscheidungsbaums</a></li>
  <li><a href="#wie-liest-man-einen-baum" id="toc-wie-liest-man-einen-baum" class="nav-link" data-scroll-target="#wie-liest-man-einen-baum"><span class="header-section-number">5.1.2</span> Wie liest man einen Baum?</a></li>
  <li><a href="#modelltraining" id="toc-modelltraining" class="nav-link" data-scroll-target="#modelltraining"><span class="header-section-number">5.1.3</span> Modelltraining</a></li>
  <li><a href="#modellspezifikation" id="toc-modellspezifikation" class="nav-link" data-scroll-target="#modellspezifikation"><span class="header-section-number">5.1.4</span> Modellspezifikation</a></li>
  </ul></li>
  <li><a href="#klassifikationsbäume" id="toc-klassifikationsbäume" class="nav-link" data-scroll-target="#klassifikationsbäume"><span class="header-section-number">5.2</span> Klassifikationsbäume</a></li>
  <li><a href="#entscheidungsbäume-in-r" id="toc-entscheidungsbäume-in-r" class="nav-link" data-scroll-target="#entscheidungsbäume-in-r"><span class="header-section-number">5.3</span> Entscheidungsbäume in R</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./classical.html">Klassisches Machine Learning</a></li><li class="breadcrumb-item"><a href="./05_tree.html"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Entscheidungsbäume</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-tree" class="quarto-section-identifier"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Entscheidungsbäume</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>Wir lernen hier nun sogenannte Entscheidungsbäume (engl. <em>Decision Trees</em>) kennen. Entscheidungsbäume gehören zur Klasse der <em>nicht-parametrischen</em> Machine Learning Modelle (wie KNN), da die Anzahl Parameter des Modells nicht von vornherein klar ist und erst nach dem Modelltraining feststeht.</p>
<p>Entscheidungsbäume können sowohl für Regressions- als auch für Klassifikationsprobleme angewendet werden. Dementsprechend werden die spezifischen Modelle Regressionsbaum bzw. Klassifikationsbaum genannt. Wir werden uns hier ausführlich mit Regressionsbäumen beschäftigen und dann sehen, dass Klassifikationsbäume lediglich eine andere Kostenfunktion optimieren, aber sonst genau gleich funktionieren.</p>
<p>Entscheidungsbäume sind in der Praxis sehr beliebt, vorausgesetzt es geht ausschliesslich um die <strong>Interpretierbarkeit</strong>: wir werden sehen, dass Entscheidungsbäume sehr einfach und ansprechend visualisiert werden können. Wenn es allerdings darum geht, möglichst gute Vorhersagen zu machen, dann werden in der Praxis kaum Entscheidungsbäume angewendet, weil sie selten zu den am besten performenden Modellen gehören. Entscheidungsbäume gelten als <strong>instabile Modelle</strong>, d.h., sie ändern sich teilweise stark, wenn sich die Trainingsdaten verändern. Bäume haben also in der Regel hohe Varianz und wenig Bias (Bias-Variance Tradeoff). Wir werden aber in <a href="06_ensemble.html" class="quarto-xref"><span>Kapitel 6</span></a> sehen, dass in der Praxis gut performende Modelle (sogenannte <em>Ensemble</em> Methoden) auf individuellen Entscheidungsbäumen aufbauen.</p>
<p>Um eine erste Intuition aufzubauen, schauen wir uns in folgender Abbildung den visuellen Unterschied zwischen dem Linearen Regressionsmodell (<a href="02_linreg.html" class="quarto-xref"><span>Kapitel 2</span></a>) und einem Entscheidungsbaum für das <strong>Regressionsproblem</strong> mit einer Input-Variable <span class="math inline">\(x_i\)</span> an:</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05_tree_files/figure-html/tree-linreg-1.png" class="img-fluid figure-img" style="width:90.0%" alt="Baum vs. Lineare Regression."></p>
<figcaption>Links: trainierter Entscheidungsbaum für ein einfaches Regressionsproblem mit einer Input-Variable (dargestellt auf der x-Achse). Rechts: trainiertes lineares Regressionsmodell für dasselbe Regressionsproblem.</figcaption>
</figure>
</div>
</div>
</div>
<p>Wie den Streudiagrammen entnommen werden kann, ist der wahre Zusammenhang zwischen dem Input <span class="math inline">\(x_i\)</span> und der Outputvariable <span class="math inline">\(y_i\)</span> hier stark nicht-linear. Der Fit des linearen Regressionsmodells (rechter Plot) ist sehr schlecht, während ein Regressionsbaum zu einem relativ guten Fit führt (linker Plot). Wir können davon bereits ableiten, dass Entscheidungsbäume <em>flexibler</em> sind als das lineare Regressionsmodell. Dementsprechend wird die Gefahr des <strong>Overfittings</strong> bei Entscheidungsbäumen auch grösser sein als beim linearen Regressionsmodell.</p>
<p>Dieses Kapitel ist teilweise inspiriert durch <span class="citation" data-cites="islr">(<a href="references.html#ref-islr" role="doc-biblioref">James u.&nbsp;a. 2021, Kap. 8</a>)</span> und <span class="citation" data-cites="Geron">(<a href="references.html#ref-Geron" role="doc-biblioref">Géron 2022, Kap. 6</a>)</span>.</p>
<section id="regressionsbäume" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="regressionsbäume"><span class="header-section-number">5.1</span> Regressionsbäume</h2>
<p>Wir widmen uns in einem ersten Schritt kurz der “Anatomie” von Entscheidungsbäumen. Danach überlegen wir uns, wie ein trainierter Entscheidungsbaum gelesen werden muss, so dass wir verstehen, wie das Modell Vorhersagen macht. In einem dritten Abschnitt befassen wir uns mit dem Modelltraining. Zu guter Letzt schauen wir uns noch kurz die mathematische Modellspezifikation an.</p>
<section id="anatomie-eines-entscheidungsbaums" class="level3" data-number="5.1.1">
<h3 data-number="5.1.1" class="anchored" data-anchor-id="anatomie-eines-entscheidungsbaums"><span class="header-section-number">5.1.1</span> Anatomie eines Entscheidungsbaums</h3>
<p>Warum spricht man bei diesem Modell überhaupt von Bäumen? Weil die Visualisierung des Modells wie ein <strong>umgekehrter Baum</strong> aussieht (siehe Abbildung unten). Dementsprechend haben die verschiedenen Teile des “Baums” auch botanisch-inspirierte Namen.</p>
<p>Wir haben einen obersten Knoten, der <strong>Root Node</strong> genannt wird. Die inneren Knoten, nach denen weitere Splits folgen, werden <strong>Internal Nodes</strong> genannt. Die untersten Knoten, nach denen keine weiteren Splits folgen, werden <strong>Leaf Nodes</strong> genannt. Die Nodes sind durch sogenannte <strong>Branches</strong> verknüpft. Die <strong>Tiefe</strong> eines Baums entspricht der Anzahl von Ebenen, auf denen Splits durchgeführt werden.</p>
<div id="fig-treeanatomy" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-treeanatomy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/AnatomieTree.png" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-treeanatomy-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;5.1: Anatomie eines Entscheidungsbaums. Das Modell hier versucht die Mieten von Schweizer Wohnungen anhand des ökonomischen Alters einer Wohnung (<code>econage</code>) und der Fläche (<code>area</code>) vorherzusagen.
</figcaption>
</figure>
</div>
<p>Doch was repräsentiert dieser Baum eigentlich? Der Baum repräsentiert eine Sequenz von <strong>Splitting-Regeln</strong> basierend auf den Input-Variablen. Wir können eine gegebene Beobachtung <span class="math inline">\(\mathbf{x}_i\)</span> vom Root Node aus durch den Baum “schicken”. Bei jedem Node im Baum wird die Beobachtung basierend auf dem konkreten Input-Variablenwert entweder links oder rechts runtergeschickt. So endet die Beobachtung irgendwann in einem Leaf Node.</p>
<p>Etwas mathematischer ausgedrückt: der Baum repräsentiert eine <strong>Segmentierung</strong> des <strong>Input Spaces</strong> in <strong>simple, rechteckige Regionen</strong>. Wir werden das im nächsten Abschnitt anhand eines Beispiels demonstrieren.</p>
</section>
<section id="wie-liest-man-einen-baum" class="level3" data-number="5.1.2">
<h3 data-number="5.1.2" class="anchored" data-anchor-id="wie-liest-man-einen-baum"><span class="header-section-number">5.1.2</span> Wie liest man einen Baum?</h3>
<p>Wir verwenden hier in der Folge den <code>housingrents</code> Datensatz, der <span class="math inline">\(n = 152\)</span> Beobachtungen zu Schweizer Wohnungen enthält. Die Outputvariable ist die Miete (<code>rent</code>). Die zwei wichtigsten Input-Variablen sind die Fläche einer Wohnung (<code>area</code>) sowie das ökonomische Alter einer Wohnung (<code>econage</code>). Eine weitere Input-Variable ist <code>nre</code>, dabei handelt es sich um eine binäre kategorische Variable, die den Wert 1 annimmt, falls eine Wohnung der Immobilienfirme NRE gehört und sonst 0. Der Datensatz ist im Dataframe <code>df</code>. Hier sind die ersten 6 Zeilen im Datensatz:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(df)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  id rooms area rent nre econage balcony
1  1     1   34  310   0      35     yes
2  2     1   35  749   0      44      no
3  3     1   50  281   0      23     yes
4  4     1   45  483   0      35      no
5  5     4   75 1510   0      32      no
6  6     1   35  515   0      43      no</code></pre>
</div>
</div>
<p>Die <a href="#fig-firstsplit" class="quarto-xref">Abbildung&nbsp;<span>5.2</span></a> (links) zeigt den Root Node sowie den ersten Split des Baums, der resultiert, wenn ein Regressionsbaum auf den <code>housingrents</code> Daten angewendet wird. Der Root Node enthält zwei Zahlen, einerseits die mittlere Miete über den ganzen Trainingsdatensatz (CHF 1240) und andererseits den Anteil von Trainingsbeobachtungen im Root Node. Dieser Anteil ist vor dem ersten Split noch 100%.</p>
<p>Der <strong>erste Split</strong> verwendet die Variable <code>econage</code> und den Splitpunkt 25. Alle Wohnungen, die min. 25 Jahre alt sind, gehen dem linken Branch entlang in den linken internen Node. Insgesamt landen so 64% der Trainingsbeobachtungen in diesem linken internen Node. Die durchschnittliche Miete für diese Beobachtungen beträgt CHF 974. Alle Wohnungen, die jünger als 25 Jahre alt sind, gehen dem rechten Branch entlang in den rechten internen Node. Das sind dementsprechend die restlichen 36% der Beobachtungen und deren mittlere Miete beträgt CHF 1724.</p>
<p><strong>Wichtig</strong>: dieser erste Split <strong>segmentiert</strong> den Input Space nun in <strong>zwei Regionen</strong> (Rechtecke), wie im rechten Teil der Abbildung dargestellt. Das wichtigste Take-Away hier ist, dass ein Split im Baum einer Segmentierung des Input Spaces entspricht! Weil wir hier nur die Variablen <code>econage</code> und <code>area</code> betrachten, können wir diesen Input Space ohne Probleme in 2D visualisieren.</p>
<div id="fig-firstsplit" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-firstsplit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/FirstSplit.PNG" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-firstsplit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;5.2: Der Baum nach dem ersten Split mit dazugehörender Segmentierung des Input Spaces (rechts).
</figcaption>
</figure>
</div>
<p>Der <strong>zweite Split</strong> geschieht beim linken internen Node (<a href="#fig-secondsplit" class="quarto-xref">Abbildung&nbsp;<span>5.3</span></a>). Dort splitten wir die 64% der Beobachtungen basierend auf der Input-Variable <code>area</code> in zwei Untergruppen. Der Splitpunkt liegt bei 63 Quadratmeter. Der linke Leaf Node enthält nun nur noch 25% der Beobachtungen und deren mittlere Miete beträgt CHF 690. Das macht Sinn, denn es handelt sich dabei um alte (25 Jahre oder älter) und kleine Wohnungen (kleiner als 63 Quadratmeter). Der rechte Leaf Node enthält 39% aller Beobachtungen und deren Mittelwert beträgt CHF 1154. Es handelt sich dabei um alte, aber relativ grosse Wohnungen.</p>
<p>Im rechten Teil der Abbildung sehen wir, dass dieser zweite Split den oberen Teil des Input Spaces weiter segmentiert in zwei Subregionen.</p>
<div id="fig-secondsplit" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-secondsplit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/SecondSplit.PNG" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-secondsplit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;5.3: Der Baum nach dem zweiten Split mit dazugehörender Segmentierung des Input Spaces (rechts).
</figcaption>
</figure>
</div>
<p>Der <strong>dritte Split</strong> geschieht im rechten internen Node und basiert ebenfalls auf der Input-Variable <code>area</code> (<a href="#fig-thirdsplit" class="quarto-xref">Abbildung&nbsp;<span>5.4</span></a>). Der Splitpunkt liegt bei 139 Quadratmeter. Dieser Split teilt also die eher neuen Wohnungen (erster Split) weiter auf in sehr grosse (grösser als 139 Quadratmeter) und weniger grosse (kleiner als 139 Quadratmeter) Wohnungen. Die mittlere Miete für die 31% der Beobachtungen im linken Leaf Node beträgt CHF 1599, während die mittlere Miete für die 5% der Beobachtungen im rechten Leaf Node CHF 2561 beträgt. Der dritte Split segmentiert das untere Reckteck im Input Space weiter.</p>
<div id="fig-thirdsplit" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-thirdsplit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/ThirdSplit.PNG" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-thirdsplit-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;5.4: Der Baum nach dem dritten Split mit dazugehörender Segmentierung des Input Spaces (rechts).
</figcaption>
</figure>
</div>
<p>Der finale Baum sowie die finale Segmentierung des Input Spaces sehen wie folgt aus:</p>
<div id="fig-finaltree" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-finaltree-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/FinalTree.PNG" class="img-fluid figure-img" style="width:100.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-finaltree-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;5.5: Der fertig trainierte Baum mit dazugehörender Segmentierung des Input Spaces (rechts).
</figcaption>
</figure>
</div>
<p>Wir sehen, dass die drei Splits zu vier Leaf Nodes führen.</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Hinweis</span>Decision Boundaries von Entscheidungsbäumen
</div>
</div>
<div class="callout-body-container callout-body">
<p>Jeder Leaf Node entspricht einer Region im Input Space. Die blau gestrichelten Linien (<a href="#fig-finaltree" class="quarto-xref">Abbildung&nbsp;<span>5.5</span></a>), welche die Regionen voneinander trennen, sind die <strong>Decision Boundaries</strong> dieses Modells. Sie begrenzen die verschiedenen Regionen, in denen wir je unterschiedliche Vorhersagen machen.</p>
</div>
</div>
<p>Die <strong>Vorhersagen</strong> unseres Baums sind nichts anderes als die <strong>mittleren Mieten in den jeweiligen Regionen</strong>. Überlegen wir uns das kurz anhand eines Beispiels: wir haben nun eine 15-jährige Wohnung mit einer Fläche von 110 Quadratmeter. Gemäss unserem Baum gehört diese Wohnung der Region <span class="math inline">\(R_3\)</span> an und dementsprechend wäre unsere Vorhersage für diese Wohnung CHF 1599. Dabei sehen wir gleich noch eine andere Eigenschaft von Entscheidungsbäumen: sie machen für alle Beobachtungen in derselben Region die gleiche Vorhersage. Oder in anderen Worten: <strong>die Vorhersagen sind pro Region konstant</strong>.</p>
<section id="fragen" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="fragen">Fragen</h4>
<ul>
<li>Was ist die Tiefe des nachfolgend abgebildeten Regressionsbaums?</li>
<li>Was würde der abgebildete Regressionsbaum für eine Wohnung mit <span class="math inline">\(econage=28\)</span>, <span class="math inline">\(area=98\)</span> und <span class="math inline">\(rooms=4\)</span> vorhersagen?</li>
<li>Wie viele Entscheidungsregionen resultieren aus dem Regressionsbaum?</li>
</ul>
<div id="fig-treedepth" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-treedepth-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="images/tree_depth.png" class="img-fluid figure-img" style="width:80.0%">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-treedepth-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Abbildung&nbsp;5.6: Visualisierung eines mit <code>R</code> trainierten Baums auf dem <code>housingrents</code> Datensatz.
</figcaption>
</figure>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tipp</span>Lösung
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Die Tiefe des Baums ist 4.</li>
<li>Die Vorhersage für diese Wohnung wäre eine Miete von CHF 1185.</li>
<li>Der Baum hat 10 Entscheidungsregionen, weil der Baum 10 Leaf Nodes hat.</li>
</ul>
</div>
</div>
</div>
</section>
</section>
<section id="modelltraining" class="level3" data-number="5.1.3">
<h3 data-number="5.1.3" class="anchored" data-anchor-id="modelltraining"><span class="header-section-number">5.1.3</span> Modelltraining</h3>
<p>Nun haben wir oben bereits gesehen, wie ein fertig trainierter Entscheidungsbaum aussieht, wie er interpretiert werden muss und wie man damit Vorhersagen machen kann. Doch wie wird das Modell trainiert?</p>
<p>Das Ziel ist, einen Regressionsbaum zu finden, dessen Entscheidungsregionen zu einer <strong>Minimierung</strong> des <strong>Mean Squared Errors</strong> (MSE) führen. Wie bei der linearen Regression (<a href="02_linreg.html" class="quarto-xref"><span>Kapitel 2</span></a>) ist also auch hier der MSE die Kostenfunktion, die es zu minimieren gilt.</p>
<p>Weil ein Regressionsbaum in jeder Region die gleichen Vorhersagen macht, schreiben wir die Kostenfunktion hier in einer speziellen Form auf:</p>
<p><span class="math display">\[
J = \frac{1}{n} \sum_{k=1}^K \sum_{i \in R_k} \left(y_i - \hat{y}_{R_k}\right)^2
\]</span></p>
<p>Die äussere Summe summiert über die Regionen <span class="math inline">\(R_1, R_2, \dots, R_K\)</span> und die innere Summe summiert <em>für jede Region</em> über die quadrierten Distanzen zwischen beobachteten und vorhergesagten Werten der Outputvariable. Ich hoffe, Sie sehen, dass es sich wirlich nur um den MSE handelt, einfach etwas speziell geschrieben wegen den Entscheidungsregionen des Baums.</p>
<p>Leider ist es hier nicht möglich dieses Minimierungsproblem genau (also analytisch) zu lösen, denn es gibt zu viele verschiedene (genauer gesagt: unendlich viele) Möglichkeiten, wie die Recktecke im Input Space angeordnet und kombiniert werden können.</p>
<p>Beim Training von Entscheidungsbäumen treffen wir deshalb einige vereinfachende Annahmen, um eine <strong>Annäherung an die optimale Lösung</strong> für das Minimum der Kostenfunktion zu finden. Der Trainingsalgorithmus wird <em>Recursive Binary Splitting</em> genannt. Dieser Algorithmus hat die Eigenschaft, dass er <strong>greedy</strong> ist. Doch was bedeutet all das?</p>
<ul>
<li><em>Binary</em>: Jeder Split hat genau einen Splitpunkt und führt deshalb zu genau zwei “Child Nodes”. Jeder Split entspricht also einer binären “entweder-oder” Entscheidung. Es gibt aus einem Split nur zwei mögliche Branches (und nicht drei, vier. oder mehr), die nach unten führen.</li>
<li><em>Recursive</em>: Jeder Split basiert auf dem vorangegangenen Split ein Level höher. Der zweite Split splittet also eine der resultierenden Regionen aus dem ersten Split. Wenn Sie nochmal zum zweiten Split beim <code>housingrents</code> Datensatz gehen, dann sehen Sie, dass der zweite Split lediglich die obere Region splittet und nicht den ganzen Input Space. Der zweite Split bezieht sich auf den ersten Split, ist also rekursiv.</li>
<li><em>Greedy</em>: wir optimieren in jedem Knoten immer nur den nächstmöglichen Split und schauen nicht weiter voraus bzw. den Baum runter. Der Algorithmus ist also in einem gewissen Sinn “geizig”.</li>
</ul>
<p>Am besten schauen wir uns diesen Trainingsalgorithmus wiederum anhand des <code>housingrents</code> Datensatzes an:</p>
<ol type="1">
<li>Wir rechnen den Wert der Kostenfunktion für jede Input-Variable und alle möglichen Splitpunkte <span class="math inline">\(s\)</span> und wählen diejenige Input-Variable mit Splitpunkt <span class="math inline">\(s\)</span>, wo <span class="math inline">\(J\)</span> minimal ist. Wir sehen, dass <code>econage</code> mit <span class="math inline">\(s=25\)</span> zum kleinsten Wert für <span class="math inline">\(J\)</span> führt. Darum ist dies unser erster Split im Baum. Gleichzeitig können wir daraus ableiten, dass <code>econage</code> die wichtigste Input-Variable im Datensatz ist. Nachfolgend die Kostenfunktionswerte für ein paar mögliche Splitpunkte:
<ul>
<li><code>econage</code> mit <span class="math inline">\(s=25\)</span>: <span class="math inline">\(SQR = 331'686.3\)</span><br>
</li>
<li><code>area</code> mit <span class="math inline">\(s=63\)</span>: <span class="math inline">\(SQR = 359'049\)</span><br>
</li>
<li><code>nre</code> mit <span class="math inline">\(s=0.5\)</span>: <span class="math inline">\(SQR = 439'140.2\)</span> (Schnittpunkt <span class="math inline">\(s=0.5\)</span> teilt die Beobachtungen in NRE und nicht-NRE)</li>
<li>Viele weitere Möglichkeiten…</li>
</ul></li>
<li>Basierend auf den zwei Regionen aus dem ersten Split, wählen wir den zweiten Split so, dass wiederum <span class="math inline">\(J\)</span> minimiert wird. Es resultieren drei Regionen. Wir sehen, dass <code>area</code> mit <span class="math inline">\(s=63\)</span> der nächstbeste Split ist.
<ul>
<li><code>area</code> mit <span class="math inline">\(s=63\)</span>: <span class="math inline">\(SQR = 298'849\)</span><br>
</li>
<li><code>nre</code> mit <span class="math inline">\(s=0.5\)</span>: <span class="math inline">\(SQR = 328'305\)</span></li>
<li>Viele weitere Möglichkeiten…</li>
</ul></li>
<li>Wir können so fortfahren bis ein <strong>Stoppkriterium</strong> erfüllt ist (z.B. maximale Tiefe des Baums erreicht).</li>
</ol>
<p>Dieser Trainingsalgorithmus hat ein grosses Problem und zwar führt er zu einer krassen Form von <strong>Overfitting</strong>. Wenn wir den Algorithmus nicht begrenzen, dann splittet der Baum frisch fröhlich weiter bis er irgendwann so viele Leaf Nodes wie Beobachtungen hat und jeder Leaf Node genau den Wert der Trainingsbeobachtung vorhersagt. Der Baum hat dann zwar einen Kostenfunktionswert von 0 auf dem Trainingsdatensatz, würde auf einem Testdatensatz jedoch katastrophal schlechte Vorhersagen machen.</p>
<p>Die Lösung ist in der Praxis zum Glück einfach: wir müssen die <strong>Komplexität</strong> des Baums mittels eines Stoppkriteriums <strong>beschränken</strong> (siehe Schritt 3 im obigen Algorithmus). Folgende Kriterien zur Beschränkung sind möglich:</p>
<ul>
<li>Maximale Tiefe des Baums</li>
<li>Minimale Anzahl Beobachtungen in einem Leaf Node</li>
<li>Minimale Anzahl Beobachtungen in einem Internen Node</li>
<li>Maximale Anzahl Leaf Nodes</li>
<li>Viele weitere…</li>
</ul>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Hinweis</span>Hyperparameter von Entscheidungsbäumen
</div>
</div>
<div class="callout-body-container callout-body">
<p>All die oben aufgelisteten Stoppkriterien können wir als <strong>Hyperparameter</strong> unseres Modells interpretieren und dementsprechend können wir den optimalen Wert für ein gegebenes Stoppkriterium mittels Hyperparameter Tuning bestimmen. Eine alternative Lösung, welche in der Literatur manchmal besprochen wird, wäre <strong>Tree Pruning</strong>.</p>
</div>
</div>
<p>In nachfolgender Abbildung trainieren wir einen Regressionsbaum auf einem simplen Datensatz mit einer Input-Variable. Wir beschränken den Baum mittels der <strong>minimalen Anzahl Beobachtungen in einem internen Knoten</strong> (<code>minsize</code> im R-Package <code>tree</code>). Wenn dieses Kriterium auf 2 gesetzt wird, dann kann der resultierende Baum die Daten perfekt abbilden.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05_tree_files/figure-html/stopp-criteria-1.png" class="img-fluid figure-img" style="width:100.0%" alt="Einfluss von Stoppkriterium auf Modellfit."></p>
<figcaption>Links: Streudiagramme der Trainingsdaten mit dem Outputwert auf der y-Achse und dem Inputwert auf der x-Achse. Die rotbraunen Kurven repräsentieren die trainierten Entscheidungsbäume auf dem Datensatz. Die vertikalen Geraden splitten den Wertebereich der Input-Variable in verschiedene Entscheidungsregionen auf. Rechts: Vorhersagegüte (gemessen als RMSE) auf Trainings- und Testdaten. Für die Testdaten wurden weitere <span class="math inline">\(n\)</span> Beobachtungen generiert, die aber nicht für das Training verwendet wurden.</figcaption>
</figure>
</div>
</div>
</div>
<section id="fragen-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="fragen-1">Fragen</h4>
<ul>
<li>Welche der obigen Abbildungen repräsentiert Overfitting?</li>
<li>Welche Underfitting?</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tipp</span>Lösung
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Die erste Abbildung ist ein klares Beispiel von Overfitting. Der Baum darf so lange weiter splitten, bis interne Nodes nur noch minimal zwei Beobachtungen enthalten. Weil die Beschränkung für interne Nodes gilt, heisst das, dass die danach folgenden Leaf Nodes nur noch je eine Beobachtung enthalten. Der Datensatz wurde so segmentiert, dass jede Entscheidungsregion nur noch eine Trainingsbeobachtung enthält. Dementsprechend ist der RMSE auf den Trainingsdaten 0.</li>
<li>Die letzte Abbildung ist ein klares Beispiel von Underfitting. In diesem Fall müssen interne Nodes mindestens 51 Beobachtungen enthalten. Mit <span class="math inline">\(n=50\)</span> darf das Modell dementsprechend nicht mal nach dem Root Node einen ersten Split machen. Das führt zu einer einzigen Entscheidungsregion, nämlich dem ganzen Wertebereich von <span class="math inline">\(x\)</span>. Und überall wird <span class="math inline">\(\bar{y}\)</span>, also der Mittelwerte über die Outputwerte im Traininsdatensatz vorhergesagt.</li>
</ul>
</div>
</div>
</div>
</section>
</section>
<section id="modellspezifikation" class="level3" data-number="5.1.4">
<h3 data-number="5.1.4" class="anchored" data-anchor-id="modellspezifikation"><span class="header-section-number">5.1.4</span> Modellspezifikation</h3>
<p>Wir hatten in diesem Abschnitt im Vergleich zu vorherigen Kapitel eine etwas komische Reihenfolge und kommen nun erst zum Schluss auf die Modellspezifikation zu sprechen. Auch dieses nicht-parametrische Modell kann mathematisch spezifiziert werden und zwar wie folgt:</p>
<p><span class="math display">\[
f(\mathbf{x}_i) = \sum_{k=1}^K \hat{y}_{R_k} \cdot \mathbb{1}_{\{\mathbf{x}_i \in R_k\}}
\]</span></p>
<p>Wir summieren also über die Entscheidungsregionen <span class="math inline">\(R_k\)</span>. <span class="math inline">\(\hat{y}_{R_k}\)</span> ist der Durchschnitt über die Werte der Outputvariable der Trainingsbeobachtungen in Region <span class="math inline">\(k\)</span>. Die Funktion <span class="math inline">\(\mathbb{1}_{\{\mathbf{x}_i \in R_k\}}\)</span> ist die sogenannte <strong>Indikatorfunktion</strong>, die nur genau dann den Wert 1 annimmt, wenn die Beobachtung <span class="math inline">\(\mathbf{x}_i\)</span> in Region <span class="math inline">\(R_k\)</span> liegt.</p>
<p>Beispiel: wir haben drei Regionen <span class="math inline">\(R_1, R_2, R_3\)</span> mit entsprechenden Mittelwerten <span class="math inline">\(\hat{y}_{R_1}=500\)</span>, <span class="math inline">\(\hat{y}_{R_2}=750\)</span> und <span class="math inline">\(\hat{y}_{R_3}=1000\)</span>. Nun haben wir eine neue Beobachtung <span class="math inline">\(\mathbf{x}_i\)</span>, die gemäss unserem Baum der Region 2 angehört. Der Funktionswert ist dementsprechend:</p>
<p><span class="math display">\[
\hat{f}(\mathbf{x}_i) = 500 \cdot 0 + 750 \cdot 1 + 1000 \cdot 0 = 750
\]</span></p>
</section>
</section>
<section id="klassifikationsbäume" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="klassifikationsbäume"><span class="header-section-number">5.2</span> Klassifikationsbäume</h2>
<p>Klassifikationsbäume funktionieren vom Prinzip her fast gleich wie Regressionsbäume. Auch hier versuchen wir den Input Space (mit rechteckigen Formen) so zu segmentieren, dass die resultierenden Regionen die kategorische Outputvariable möglichst gut klassifizieren. Es gibt jedoch <strong>zwei zentrale Unterschiede</strong> im Vergleich zum Regressionsproblem:</p>
<ul>
<li><p>Die <strong>Vorhersage</strong> in einer Region <span class="math inline">\(R_k\)</span> entspricht nicht wie beim Regressionsbaum dem Mittelwert über die Outputvariable, sondern der <strong>am häufigsten vorkommenden Output-Kategorie</strong> in der Entscheidungsregion <span class="math inline">\(R_k\)</span>.</p></li>
<li><p>Der Trainingsalgorithmus minimiert nicht den MAE, sondern den <strong>Gini Index</strong>. Der Gini Index ist ein Mass für die “Reinheit” in einem Leaf Node. Warum ist das ein gutes Gütekriterium? Ein perfekter Baum hat in jedem Leaf Node nur noch Beobachtungen einer Kategorie. In dem Fall ist die “Reinheit” maximal. Schauen wir uns doch kurz die Formel für die Berechnung des Gini Indexes (für die <span class="math inline">\(k\)</span>-te Entscheidungsregion <span class="math inline">\(R_k\)</span>) an:</p>
<p><span class="math display">\[
G_k = \sum_{l=1}^L \hat{p}_{kl} \cdot (1-\hat{p}_{kl})
\]</span> <span class="math inline">\(\hat{p}_{kl}\)</span> beschreibt hier den Anteil der <span class="math inline">\(l\)</span>-ten Output-Kategorie in der <span class="math inline">\(k\)</span>-ten Entscheidungsregion <span class="math inline">\(R_k\)</span>. Die Gesamtkostenfunktion ist dann einfach die Summe über die Gini Indizes in den verschiedenen Regionen, also <span class="math inline">\(\sum_k G_k\)</span>.</p></li>
</ul>
<section id="fragen-2" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="fragen-2">Fragen</h4>
<ul>
<li>Wir haben ein binäres Klassifikationsproblem und wollen vorhersagen, ob jemand zahlungsunfähig wird oder nicht. In einer Entscheidungsregion des Baums haben wir 20 Beobachtungen, davon 15, die nicht zahlungsunfähig werden. Was ist der Wert des Gini Indexes in dieser Region?</li>
<li>Welchen Wert hat der Gini Index, wenn eine Entscheidungsregion nur noch Beobachtungen einer Kategorie enthält?</li>
</ul>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tipp</span>Lösung
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Die Lösung für die erste Frage rechnet sich wie folgt:</p>
<p><span class="math display">\[\begin{align}
G_k &amp;= \sum_{l=1}^L \hat{p}_{kl} \cdot (1-\hat{p}_{kl})\\
&amp;= \frac{5}{20} \cdot \left(1-\frac{5}{20}\right) + \frac{15}{20} \cdot \left(1-\frac{15}{20}\right)\\
&amp;= 2 \cdot \frac{5}{20} \cdot \frac{15}{20}\\
&amp;= \frac{150}{400} = 0.375
\end{align}\]</span></p>
<p>Wenn eine Entscheidungsregion nur noch Beobachtungen einer Kategorie enthält, dann ist deren Anteil <span class="math inline">\(\hat{p}=1\)</span>. Daraus ergibt sich folgende Gini Index Berechnung: <span class="math inline">\(1 \cdot (1 - 1) + 0 \cdot (1 - 0) = 0\)</span>. Das ist auch gut so, denn wir wollen den Gini Index als eine Kostenfunktion interpretieren. Wir haben nur dann Kosten von 0, wenn eine Entscheidungsregion nur noch Beobachtungen einer Output-Kategorie enthält.</p>
</div>
</div>
</div>
<div class="callout callout-style-default callout-caution callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-6-contents" aria-controls="callout-6" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Vorsicht</span>Entropie (optional)
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-6" class="callout-6-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Eine Alternative zum Gini Index als Kostenfunktion ist die <strong>Entropie</strong>. Für die <span class="math inline">\(k\)</span>-te Entscheidungsregion <span class="math inline">\(R_k\)</span> rechnet sie sich wie folgt:</p>
<p><span class="math display">\[
H_k = - \sum_{l=1}^L \hat{p}_{kl} \cdot \log_2\,\left(\hat{p}_{kl}\right)
\]</span> Die Unterschiede zwischen dem Gini Index und Entropie als Kostenfunktion sind in der Praxis meist nicht von grosser Relevanz, aber es kann sich trotzdem lohnen, beide auszuprobieren und mittels Cross-Validation zu überprüfen, welche davon besser funktioniert.</p>
</div>
</div>
</div>
<p>Drei wichtige Punkte gilt es noch zu erwähnen:</p>
<ul>
<li>Wie bei der logistischen Regression gesehen (<a href="03_linclass.html" class="quarto-xref"><span>Kapitel 3</span></a>), geben uns die meisten Klassifkationsmodelle eine <strong>Wahrscheinlichkeit</strong> zurück, dass die Outputvariable <span class="math inline">\(y_i\)</span> der ersten Kategorie angehört (<span class="math inline">\(y_i=1\)</span>). Das ist auch für Klassifikationsbäume möglich. Anstelle der am häufigsten vorkommenden Kategorie (<em>hard prediction</em>) können wir uns vom Baum auch die <strong>relativen Anteile</strong> der Kategorien in einer Entscheidungsregion (bzw. einem Leaf Node) ausgeben lassen (<em>soft predictions</em>). Diese Anteil können als Wahrscheinlichkeiten für die verschiedenen Kategorien interpretiert werden.</li>
<li>Ein Klassifikationsbaum ist nicht auf eine binäre Outputvariablen limitiert und kann problemlos auf <strong>mehrklassige Outputvariablen</strong> angewendet werden.</li>
<li><strong>Kategoriale Input-Variablen</strong> sind übrigens auch problemlos in Bäumen verwendbar. Beispiel: wir haben eine Input-Variable <em>Augenfarbe</em> mit drei möglichen Kategorien “blau”, “grün” und “braun”. Der Trainingsalgorithmus testet in diesem Fall alle möglichen Splits, hier sind es folgende drei:
<ul>
<li>“blau” vs.&nbsp;“grün” oder “braun”</li>
<li>“grün” vs.&nbsp;“blau” oder “braun”</li>
<li>“braun” vs.&nbsp;“blau” oder “grün”.</li>
</ul></li>
</ul>
<p>Schauen wir uns zum Schluss dieses Abschnitts an, wie ein Klassifikationsbaum unser Beispiel mit zwei Input-Variablen aus <a href="03_linclass.html" class="quarto-xref"><span>Kapitel 3</span></a> segmentiert. Ich habe hier das R-Package <code>tree</code> verwendet und das Argument <code>minsize</code> auf 10 gesetzt (d.h., ein interner Knoten darf nicht weniger als 10 Beobachtungen enthalten):</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="05_tree_files/figure-html/tree-2D-1.png" class="img-fluid figure-img" style="width:60.0%" alt="DB für zwei Input-Variablen (Klassifikationsbaum)."></p>
<figcaption>Decision Boundary für einen Threshold von 50% (bzw. 0.5) für einen Klassifikationsbaum mit <code>minsize = 10</code>.</figcaption>
</figure>
</div>
</div>
</div>
<p>Wir sehen hier auch gleich zwei Probleme von Bäumen:</p>
<ul>
<li>Die resultierende Decision Boundary ist viel zu kompliziert für dieses Beispiel (<strong>Overfitting</strong>).</li>
<li>Die Decision Boundary ist begrenzt auf lineare Segmente, die in einem <strong>rechten Winkel zu den Achsen</strong> verlaufen. Das ist eine starke Limitierung dieses Modells.</li>
</ul>
<p>Nachfolgend der gefittete Baum:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>node), split, n, deviance, yval
      * denotes terminal node

 1) root 50 12.5000 0.5000  
   2) X1 &lt; 5.25263 27  4.0740 0.1852  
     4) X2 &lt; 4.66245 14  0.0000 0.0000 *
     5) X2 &gt; 4.66245 13  3.0770 0.3846  
      10) X2 &lt; 5.92184 6  1.3330 0.6667 *
      11) X2 &gt; 5.92184 7  0.8571 0.1429 *
   3) X1 &gt; 5.25263 23  2.6090 0.8696  
     6) X2 &lt; 5.22556 9  2.0000 0.6667 *
     7) X2 &gt; 5.22556 14  0.0000 1.0000 *</code></pre>
</div>
</div>
</section>
<section id="frage" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="frage">Frage</h4>
<p>Versuchen Sie den obigen R-Output gut zu verstehen. Sehen Sie die Splits im Input Space oben repräsentiert. Warum fehlt der Split repräsentiert durch <code>6)</code> und <code>7)</code>?</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center collapsed" data-bs-toggle="collapse" data-bs-target=".callout-7-contents" aria-controls="callout-7" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Tipp</span>Lösung
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-7" class="callout-7-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Der <strong>erste Split</strong> des Baums ist im R-Output durch <code>2)</code> und <code>3)</code> repräsentiert und bezieht sich auf die erste Input-Variable. Im Input Space entspricht der Split dem horizontalen Segment auf der Höhe 5.25.</p>
<p>Der <strong>zweite und dritte Split</strong> des Baums ist im R-Output durch <code>4)</code> und <code>5)</code> respektive <code>6)</code> und <code>7)</code> repräsentiert. Beide beziehen sich auf die zweite Input-Variable.</p>
<p>Der zweite Split ist im Input Space repräsentiert durch das vertikale Segment auf der Höhe 4.66 (im unteren, roten Teil des Input Space).</p>
<p>Der dritte Split ist im Input Space <strong>nicht</strong> repräsentiert. Warum nicht? Wenn Sie den Split in <code>6)</code> und <code>7)</code> genau anschauen, dann sehen Sie, dass in beiden Regionen der Anteil der blauen Beobachtungen über 0.5 liegt (0.67 und 1.0). Das bedeutet, dass dieser Split mit einem Threshold von 0.5 keinen Einfluss auf die Decision Boundary hat.</p>
<p>Der <strong>vierte Split</strong> des Baums ist im R-Output durch <code>10)</code> und <code>11)</code> repräsentiert und bezieht sich auf die zweite Input-Variable. Im Input Space entspricht der Split dem vertikalen Segment auf der Höhe 5.92.</p>
</div>
</div>
</div>
</section>
</section>
<section id="entscheidungsbäume-in-r" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="entscheidungsbäume-in-r"><span class="header-section-number">5.3</span> Entscheidungsbäume in R</h2>
<p>Wir illustrieren die Anwendung von Entscheidungsbäumen anhand des <strong>Heart</strong> Datensatzes, der auch in <span class="citation" data-cites="islr">(<a href="references.html#ref-islr" role="doc-biblioref">James u.&nbsp;a. 2021, Kap. 8</a>)</span> verwendet wird und sich sehr gut eignet. Der ursprüngliche Datensatz kann vom <a href="https://archive.ics.uci.edu/ml/datasets/heart+disease">UC Irvine ML Repository</a> heruntergeladen werden. Eine vorverarbeitete Version des Datensatzes, die wir unten verwenden, kann <a href="data/heart.rds">hier</a> heruntergeladen werden.</p>
<p>Der Datensatz enthält diverse Angaben zu 303 Patientinnen und Patienten, die mit Herzproblemen in ein Spital eingeliefert wurden. Unser Ziel ist es, aufgrund von verschiedenen Attributen vorherzusagen, ob eine Patientin oder ein Patient eine Herzerkrankung hat.</p>
<p>Der Datensatz umfasst folgende Variablen:</p>
<ul>
<li><code>age</code>: Alter</li>
<li><code>sex</code>: Geschlecht</li>
<li><code>cp</code>: Art der Brustkorbschmerzen, 4 Kategorien</li>
<li><code>trestbps</code>: systolischer Blutdruck</li>
<li><code>chol</code>: Cholesterin-Wert im Blut</li>
<li><code>fbs</code>: Blutzuckerwert (gemessen am Morgen auf nüchternen Magen) grösser als 120 mg/dl? (yes / no)</li>
<li><code>restecg</code>: EKG Resultate, 3 Kategorien</li>
<li><code>thalach</code>: Maximale erreichte Herzfrequenz</li>
<li><code>exang</code>: Durch Sport ausgelöstes Angina (reduzierte Blutzufuhr zum Herz)? (yes / no)</li>
<li><code>oldpeak</code>: Parameter der EKG Messung</li>
<li><code>slope</code>: Parameter der EKG Messung, 3 Kategorien</li>
<li><code>ca</code>: Anzahl Hauptarterien</li>
<li><code>thal</code>: Thallium Stress Test Resultate (wie gut fliesst Blut zum Herz?), 3 Kategorien</li>
<li><code>hd</code>: Herzerkrankung? (yes / no) - Outputvariable</li>
</ul>
<p>Laden wir als erstes die nötigen R-Packages.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(rpart.plot)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidymodels)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Als nächstes überprüfen wir kurz, ob der Dataframe fehlende Werte enthält:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fehlende Werte?</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="fu">sapply</span>(heart, <span class="cf">function</span>(x) <span class="fu">sum</span>(<span class="fu">is.na</span>(x)))</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     age      sex       cp trestbps     chol      fbs  restecg  thalach 
       0        0        0        0        0        0        0        0 
   exang  oldpeak    slope       ca     thal       hd 
       0        0        0        4        2        0 </code></pre>
</div>
</div>
<p>Wir sehen, dass die Variable <code>ca</code> 4 fehlende Werte und die Variable <code>thal</code> zwei fehlende Werte enthält. Ein weiterer Vorteil von Entscheidungsbäumen ist, dass sie gut mit fehlenden Werten umgehen können. Was effektiv passiert, ist folgendes: wenn in einem Split eine Variable verwendet wird, welche fehlende Werte enthält, dann wird für die Beobachtungen mit fehlenden Werten eine andere Variable (sogenanntes <strong>Surrogat</strong>) für den Split verwendet, welche möglichst ähnliche Entscheidungen trifft wie die eigentliche Splitvariable.</p>
<p>Als nächstes stellen wir sicher, dass wir keine starke <strong>Imbalance</strong> in der Outputvariable haben:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ist der Datensatz balanced?</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>heart <span class="sc">|&gt;</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(hd) <span class="sc">|&gt;</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">prop =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n))</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   hd   n      prop
1  no 164 0.5412541
2 yes 139 0.4587459</code></pre>
</div>
</div>
<p>Das sieht gut aus. Ein Verhältnis von 54% Nein (keine Herzerkrankungen) zu 46% Ja (Herzerkrankungen) in der Outputvariable ist akzeptabel.</p>
<p>Wir machen hier ausnahmsweise <strong>keinen Train-Test Split</strong>, da es hier lediglich darum geht, die Anwendung von Entscheidungsbäumen zu demonstrieren. In einem richtigen ML-Projekt würden wir allerdings spätestens hier einen Train-Test Split vollziehen.</p>
<p>Stattdessen erstellen wir 5 Folds, um die optimalen Hyperparameter mit 5-Fold Cross-Validation zu finden.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Seed für Reproduzierbarkeit</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co"># 5-Fold CV</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a>folds <span class="ot">&lt;-</span> <span class="fu">vfold_cv</span>(heart, <span class="at">v =</span> <span class="dv">5</span>, <span class="at">repeats =</span> <span class="dv">1</span>, <span class="at">strata =</span> hd)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Nun spezifizieren wir das Modell mit der Funktion <code>decision_tree()</code> aus <code>tidymodels</code>. Wir werden hier die Hyperparameter <code>tree_depth</code> (Tiefe des Baums) und <code>min_n</code> (minimale Anzahl Beobachtungen in einem Node) tunen. Den Hyperparameter <code>cost_complexity</code> setzen wir auf 0 (diesen würden wir für das Pruning eines Baums verwenden). Wir spezifizieren ausserdem, dass es sich um ein Klassifikationsproblem handelt und dass wir das R-Package <code>rpart</code> für das Fitting verwenden wollen.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Spezifikation des Classification Trees</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>dt_mod <span class="ot">&lt;-</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">decision_tree</span>(<span class="at">tree_depth =</span> <span class="fu">tune</span>(), <span class="at">min_n =</span> <span class="fu">tune</span>(), <span class="at">cost_complexity =</span> <span class="dv">0</span>) <span class="sc">|&gt;</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_mode</span>(<span class="st">"classification"</span>) <span class="sc">|&gt;</span></span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">set_engine</span>(<span class="st">"rpart"</span>)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Im Workflow definieren wir unter anderem die Modellgleichung <code>hd ~ .</code>, d.h. die Variable <code>hd</code> ist die Outputvariable und alle anderen werden als Input-Variablen verwendet.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Workflow</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>dt_workflow <span class="ot">&lt;-</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">workflow</span>() <span class="sc">|&gt;</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_model</span>(dt_mod) <span class="sc">|&gt;</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">add_formula</span>(hd <span class="sc">~</span> .)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Wir erstellen einen Tuning Grid für die beiden Hyperparameter, die wir tunen wollen:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tuning Grid</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>dt_grid <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">tree_depth =</span> <span class="fu">seq</span>(<span class="dv">1</span>, <span class="dv">10</span>, <span class="at">by =</span> <span class="dv">2</span>), <span class="at">min_n =</span> <span class="fu">seq</span>(<span class="dv">10</span>, <span class="dv">30</span>, <span class="dv">5</span>))</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Wie sieht Grid aus?</span></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(dt_grid)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   tree_depth min_n
1           1    10
2           3    10
3           5    10
4           7    10
5           9    10
6           1    15
7           3    15
8           5    15
9           7    15
10          9    15
11          1    20
12          3    20
13          5    20
14          7    20
15          9    20
16          1    25
17          3    25
18          5    25
19          7    25
20          9    25
21          1    30
22          3    30
23          5    30
24          7    30
25          9    30</code></pre>
</div>
</div>
<p>Nun sind wir bereit, das Modell zu fitten und das Hyperparameter Tuning durchzuführen. Wir verwenden sowohl die Fläche unter der ROC-Kurve als auch die Accuracy, um die Modellgüte zu messen:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tuning / Model Fitting</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>dt_res <span class="ot">&lt;-</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>  dt_workflow <span class="sc">|&gt;</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tune_grid</span>(</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">resamples =</span> folds,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">grid =</span> dt_grid,</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">control =</span> <span class="fu">control_grid</span>(<span class="at">save_pred =</span> <span class="cn">TRUE</span>, <span class="at">save_workflow =</span> <span class="cn">TRUE</span>),</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>    <span class="at">metrics =</span> <span class="fu">metric_set</span>(roc_auc, accuracy))</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Schauen wir uns doch die besten 10 Hyperparameter Werte gemäss ROC AUC Kriterium an:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Wir sortieren die Hyperparameter Spezifikationen nach ROC AUC</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>dt_res <span class="sc">|&gt;</span></span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">show_best</span>(<span class="at">metric =</span> <span class="st">"roc_auc"</span>, <span class="at">n =</span> <span class="dv">10</span>) <span class="sc">|&gt;</span></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(mean))</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 10 × 8
   tree_depth min_n .metric .estimator  mean     n std_err .config         
        &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;      &lt;dbl&gt; &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;           
 1          5    20 roc_auc binary     0.824     5  0.0223 pre0_mod13_post0
 2          7    20 roc_auc binary     0.824     5  0.0223 pre0_mod18_post0
 3          9    20 roc_auc binary     0.824     5  0.0223 pre0_mod23_post0
 4          3    20 roc_auc binary     0.815     5  0.0191 pre0_mod08_post0
 5          3    25 roc_auc binary     0.815     5  0.0191 pre0_mod09_post0
 6          3    30 roc_auc binary     0.815     5  0.0191 pre0_mod10_post0
 7          7    15 roc_auc binary     0.813     5  0.0281 pre0_mod17_post0
 8          9    15 roc_auc binary     0.813     5  0.0281 pre0_mod22_post0
 9          3    10 roc_auc binary     0.812     5  0.0241 pre0_mod06_post0
10          3    15 roc_auc binary     0.812     5  0.0241 pre0_mod07_post0</code></pre>
</div>
</div>
<p>Nun fitten wir den optimalen Decision Tree (<code>tree_depth = 5</code> und <code>min_n = 20</code>) auf dem ganzen Datensatz, so dass wir den letzten optimalen Fit kriegen:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Last Fit (auf ganzem Trainingsdatensatz)</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>last_dt_fit <span class="ot">&lt;-</span> <span class="fu">fit_best</span>(dt_res)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Wir können uns den Last Fit mal ausgeben lassen:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Last Fit</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>last_dt_fit</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>══ Workflow [trained] ══════════════════════════════════════════════════════════
Preprocessor: Formula
Model: decision_tree()

── Preprocessor ────────────────────────────────────────────────────────────────
hd ~ .

── Model ───────────────────────────────────────────────────────────────────────
n= 303 

node), split, n, loss, yval, (yprob)
      * denotes terminal node

 1) root 303 139 no (0.54125413 0.45874587)  
   2) thal=normal 167  38 no (0.77245509 0.22754491)  
     4) cp=atypical angina,non-anginal pain 100   9 no (0.91000000 0.09000000) *
     5) cp=typical angina,asymptomatic 67  29 no (0.56716418 0.43283582)  
      10) ca&lt; 0.5 40   9 no (0.77500000 0.22500000)  
        20) age&lt; 51.5 15   0 no (1.00000000 0.00000000) *
        21) age&gt;=51.5 25   9 no (0.64000000 0.36000000)  
          42) exang=no 17   4 no (0.76470588 0.23529412) *
          43) exang=yes 8   3 yes (0.37500000 0.62500000) *
      11) ca&gt;=0.5 27   7 yes (0.25925926 0.74074074)  
        22) sex=female 7   3 no (0.57142857 0.42857143) *
        23) sex=male 20   3 yes (0.15000000 0.85000000) *
   3) thal=fixed defect,reversable defect 136  35 yes (0.25735294 0.74264706)  
     6) cp=typical angina,atypical angina,non-anginal pain 46  21 no (0.54347826 0.45652174)  
      12) ca&lt; 0.5 29   8 no (0.72413793 0.27586207)  
        24) oldpeak&lt; 0.1 7   0 no (1.00000000 0.00000000) *
        25) oldpeak&gt;=0.1 22   8 no (0.63636364 0.36363636)  
          50) chol&lt; 259.5 13   3 no (0.76923077 0.23076923) *
          51) chol&gt;=259.5 9   4 yes (0.44444444 0.55555556) *
      13) ca&gt;=0.5 17   4 yes (0.23529412 0.76470588) *
     7) cp=asymptomatic 90  10 yes (0.11111111 0.88888889)  
      14) oldpeak&lt; 0.55 22   8 yes (0.36363636 0.63636364)  
        28) chol&lt; 237.5 12   5 no (0.58333333 0.41666667) *
        29) chol&gt;=237.5 10   1 yes (0.10000000 0.90000000) *
      15) oldpeak&gt;=0.55 68   2 yes (0.02941176 0.97058824) *</code></pre>
</div>
</div>
<p>Hmm, etwas schwierig da den Überblick zu behalten. Mithilfe des R-Packages <code>rpart.plot</code> können wir den finalen Baum plotten, so dass er einfacher lesbar wird:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot des finalen Baums</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>last_dt_fit <span class="sc">|&gt;</span></span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">extract_fit_engine</span>() <span class="sc">|&gt;</span></span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rpart.plot</span>()</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="05_tree_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Jeder Knoten im Baum enthält drei Informationen: erstens die Vorhersage, die der Baum in diesem Knoten machen würde, zweitens den relativen Anteil an Beobachtungen mit Herzerkrankung und drittens den gesamten relativen Anteil von Beobachtungen, welche in diesem Knoten landen. Anhand der Anzahl Leaf Nodes sehen wir, dass dieser Baum den Input Space in <strong>13 Entscheidungsregionen</strong> aufteilt.</p>
<p>Nun plotten wir noch die ROC-Kurve für das finale Modell:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ROC Kurve für finalen Baum</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a>dt_auc <span class="ot">&lt;-</span><span class="fu">augment</span>(last_dt_fit, <span class="at">new_data =</span> heart) <span class="sc">|&gt;</span></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">roc_curve</span>(hd, .pred_yes, <span class="at">event_level =</span> <span class="st">"second"</span>)</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a><span class="co"># ROC Kurve</span></span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a><span class="fu">autoplot</span>(dt_auc)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="05_tree_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Mithilfe der Funktion <code>predict()</code> können wir basierend auf dem finalen Baum Vorhersagen für neue Beobachtungen machen. Hier tun wir das der Einfachheit halber für die fünfte Beobachtung im Datensatz <code>heart</code>. <strong>Wichtig</strong>: mit <code>type = "class"</code> kriegen wir eine <em>hard prediction</em> für die Beobachtung, während wir mit <code>type = "prob"</code> die <em>soft prediction</em> kriegen, also die Anteile von “yes” und “no” im Leaf Node (bzw. der Entscheidungsregion), in dem die fünfte Beobachtung landet.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Vorhersagen</span></span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(last_dt_fit, <span class="at">new_data =</span> heart[<span class="dv">5</span>, ], <span class="at">type =</span> <span class="st">"class"</span>)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 1
  .pred_class
  &lt;fct&gt;      
1 no         </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">predict</span>(last_dt_fit, <span class="at">new_data =</span> heart[<span class="dv">5</span>, ], <span class="at">type =</span> <span class="st">"prob"</span>)</span></code></pre></div><button title="In die Zwischenablage kopieren" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  .pred_no .pred_yes
     &lt;dbl&gt;     &lt;dbl&gt;
1     0.91      0.09</code></pre>
</div>
</div>
<p>Wir sind uns bei dieser Person ziemlich sicher, dass <strong>keine Herzerkrankung</strong> vorliegt.</p>


<div id="refs" class="references csl-bib-body hanging-indent" role="list" style="display: none">
<div id="ref-Geron" class="csl-entry" role="listitem">
Géron, Aurélien. 2022. <em>Hands-On Machine Learning with Scikit-Learn, Keras, and TensorFlow: Concepts, Tools, and Techniques to Build Intelligent Systems</em>. 3. Aufl. O’Reilly.
</div>
<div id="ref-islr" class="csl-entry" role="listitem">
James, Gareth, Daniela Witten, Trevor Hastie, und Robert Tibshirani. 2021. <em>An Introduction to Statistical Learning: with Applications in R</em>. 2. Aufl. Springer. <a href="https://www.statlearning.com/">https://www.statlearning.com/</a>.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Kopiert");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Kopiert");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./04_pipeline.html" class="pagination-link" aria-label="Hyperparameter Tuning und Evaluation">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Hyperparameter Tuning und Evaluation</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./06_ensemble.html" class="pagination-link" aria-label="Ensembles">
        <span class="nav-page-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Ensembles</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Copyright 2026, Martin Sterchi</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="https://www.martinsterchi.ch">
<p>https://www.martinsterchi.ch</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>