{
  "hash": "a1debf3c4451668bac2bb00194dd69ec",
  "result": {
    "engine": "knitr",
    "markdown": "# Convolutional Neural Networks {#sec-cnn}\n\n\n::: {.cell}\n\n:::\n\n\nIm zweiten Kapitel zum Thema Deep Learning befassen wir uns nun mit dem Thema **Computer Vision** und den dazugehörenden **Convolutional Neural Networks** (CNNs). Computer Vision heisst, wir wollen einem Computer bzw. einem Modell das \"Sehen\" beibringen. Das Modell soll zum Beispiel Gesichter erkennen, Bilder klassifizieren oder Objekte auf Bildern oder in Videos lokalisieren. Die ersten richtig grossen Durchbrüche von Deep Learning fanden ab 2010 im Bereich Computer Vision statt.\n\n## Modellspezifikation\n\nGanz grob funktionieren CNNs so, dass sie in den ersten paar Layers nach dem Input Layer **kleine Muster** (sogenannte *low-level features*) identifizieren, z.B. horizontale oder vertikale Segmente, Halbkreise, Kreise, etc. In späteren Layers werden diese kleinen Muster zu grösseren, komplexeren Muster (sogenannte *high-level features*) kombiniert. Auch hier findet also ein autonomer (und automatischer) Feature Engineering Prozess statt. Am Schluss macht das CNN seine Vorhersagen basierend auf den abstrakten Muster und Formen, die es im Bild erkannt hat.\n\nVielleicht wundern Sie sich, warum wir dazu nicht die ANN Modelle aus @sec-ann verwenden. Das Problem ist, dass ANNs, wie wir sie kennen gelernt haben, nur für ganz kleine Bilder (die MNIST Bilder hatten eine ganz kleine Auflösung von $28 \\times 28$ Pixels) funktionieren. Für Bilder mit einer höheren Auflösung hätte unser ANN schnell mal viel zu viele Parameter und wäre **nicht mehr trainierbar**.\n\n#### Frage {.unnumbered}\n\nWie viele Parameter (ohne Bias Terms) hätte ein ANN zwischen Input Layer und Hidden Layer, wenn die Bilder eine Auflösung von $200 \\times 200$ Pixels haben und wir 100 Neurons im Hidden Layer haben?\n\n* 100\n* 4 Mio.\n* 40'000\n* 400'000\n\n::: {.callout-tip collapse=\"true\"}\n## Lösung\n\nDieses ANN hätte 40'000 Input Neurons (so viele wie das Bild Pixels hat) und dementsprechend $100 \\cdot 40'000 = 4 \\text{Mio.}$ Parameter.\n:::\n\nUm dieses Problem zu beheben, wurden CNNs entwickelt. Wie CNNs funktionieren und was für Arten von Layers sie enthalten, werden wir uns in diesem ersten Abschnitt zu CNNs anschauen.\n\n### Farbbilder\n\nWir werden hier nun mit **farbigen Bildern** arbeiten. Im Fall von *Grayscale* Bildern (wie bei MNIST) konnte jedes Bild durch einen 2D-Array (= Matrix) dargestellt werden. Für farbige Bilder brauchen wir drei Dimensionen, denn jedes Pixel in einem Bild wird definiert durch den Anteil von Rot, Blau und Grün (RBG). Wir können uns ein farbiges Bild als drei Matrizen, welche übereinandergelegt werden, vorstellen:\n\n![Ein Farbbild kann man sich als drei übereinander gelegte Matrizen, welche den Rot-, Grün- und Blauanteil definieren vorstellen. Man spricht oft auch von den drei Farbchannels. Die meisten realen Bilder haben selbstverständlich eine viel höhere Auflösung (in den drei Farbchannels) als $12 \\times 12$ Pixels.](images/colorImage.png){width=50% #fig-colimg}\n\nIm folgenden Code Block können Sie beispielsweise die Dimensionen eines Farbbilds eines Zebras (Quelle: Joachim Huber, via Wikimedia Commons, CC BY-SA 2.0) anschauen. Das Bild wurde im Hintergrund bereits geladen und kann hier als `zebra` aufgerufen werden:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Dimensionen des Bilds\ndim(zebra)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 1277 1920    3\n```\n\n\n:::\n:::\n\n\nDas Bild ist also 1277 Pixel hoch, 1920 Pixel brei und die dritte Dimension beschreibt die drei Farbchannels.\n\nWir können das Bild selbstverständlich auch direkt in R plotten:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Leere Plot-Hülle\nplot(0:1, 0:1, type = \"n\", ann = FALSE, axes = FALSE)\n\n# Bild plotten\nrasterImage(zebra, 0, 0, 1, 1)\n```\n\n::: {.cell-output-display}\n![](09_cnn_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n**Wichtig**: Anders als bei den ANNs müssen wir bei einem CNN das Bild *nicht* in einen langen Input-Datenvektor umformen (bzw. *flatten*). Wir werden das Bild also in der oben schematisch dargestellten 3D Struktur in das CNN einspeisen können. Warum das so ist, werden wir weiter unten sehen.\n\n### Convolution Layers\n\nUm genau zu verstehen, was in einem **Convolution Layer** passiert, werden wir uns hier der Einfachheit halber wieder ein MNIST Beispiel anschauen. Im MNIST haben wir *Grayscale* Bilder und darum kann das Bild durch eine Matrix dargestellt werden und wir müssen uns vorerst nicht mit den Farbchannels herumschlagen. Die meisten CNNs sind aber für Farbbilder (mit drei Farbchannels) konzipiert.\n\n#### Convolution anhand von MNIST\n\nIn einem Convolution Layer **schieben** wir mehrere sogenannte **Convolution Filters** über ein Bild. Diese Filter haben das Ziel kleine Muster und Formen im Bild zu erkennen. Doch wie sieht so ein Filter aus? Ein Convolution Filter kann durch eine kleine Matrix dargestellt werden. Häufig werden $3 \\times 3$ Filter (also $3 \\times 3$ Matrizen) verwendet. Im Beispiel weiter unten werden wir folgenden einfachen Filter verwenden:\n\n$$\n\\begin{bmatrix}\n0 & 0 & 0\\\\\n1 & 1 & 1\\\\\n0 & 0 & 0\n\\end{bmatrix}\n$$\nWir werden sehen, dass sich dieser Convolution Filter eignet, um **horizontale Segmente** im Bild zu erkennen. Überlegen Sie sich kurz anhand der Elemente in der Matrix, warum dieser Filter dafür geeignet sein könnte.\n\nIn der folgenden Abbildung schauen wir uns wie in @sec-ann das Bild der handgeschriebenen \"7\" an. Der Prozess der Convolution beginnt beim Pixel links oben. Wir legen den Filter über das Bild, so dass die **Mitte des Filters** genau auf dem Pixel links oben liegt. Dann multiplizieren wir die Werte des Filters mit den darunter liegenden Pixelwerten und summieren die Werte aller Multiplikationen auf. Der resultierende Wert ist dann der Pixelwert links oben im Output (rechter Teil der Abbildung mit dem Untertitel *Convolution*). Damit das auch bei allen Pixels am Rand des Bilds funktioniert, umrahmen wir das Bild mit Nullen. Dieser Schritt wird in der Praxis **Zero-Padding** genannt. Wir sehen in untenstehender Abbildung, dass die Convolution für das Pixel links oben zu einem Wert von 0 führt:\n\n![Prozess der Convolution anhand eines vereinfachten MNIST Bilds der handgeschriebenen Zahl 7.](images/conv1.png){width=80% #fig-conv1}\n\nNun schieben wir den Convolution Filter über das Bild bis wir die Convolution für jedes Pixel berechnet haben. In der nächsten Abbildung schauen wir uns (als weiteres Beispiel) die Convolution für das Pixel in der dritten Zeile und fünften Spalte an. Hier ist der Output der Convolution nun 3:\n\n![Prozess der Convolution anhand eines vereinfachten MNIST Bilds der handgeschriebenen Zahl 7. Das zentrale Pixel unter dem Filter ist das Pixel in der dritten Zeile und fünften Spalte. Der Output der Convolution ist 3.](images/conv2.png){width=80% #fig-conv2}\n\nEine animierte Version des Convolution Prozesses sieht wie folgt aus:\n\n![Das GIF zeigt, wie ein Convolution Filter über das Bild (in Blau) geschoben wird. Die grünze Matrix enthält die Resultate der Convolution. Quelle des GIFs: Vincent Dumoulin und Francesco Visin, via Wikimedia Commons, MIT.](images/Convolution_arithmetic.gif){width=50% #fig-convgif}\n\nSobald wir den Filter über das ganze Bild geschoben haben und für jedes Pixel die Convolution berechnet haben, kriegen wir den vollständigen **Output dieses Filters** (rechts):\n\n![Rechts der Output des Convolution Filters nachdem er vollständig über das Bild links geschoben wurde.](images/conv3.png){width=80% #fig-conv3}\n\nSie sehen, dass im Output (rechts) die horizontalen Segmente hervorgehoben sind, weil sie höhere Convolution Resultate erzielten (max. den Wert 3). Der Filter hat also tatsächlich dieses Muster erkennen können. Allgemein gilt: der Filter gibt dann grosse Werte zurück, wenn das Muster in der jeweiligen $3 \\times 3$ Submatrix des Bilds dem Filter ähnlich ist. Wir haben hier den Filter jeweils um ein Pixel nach rechts (oder unten) verschoben. In diesem Fall spricht man von einem **Stride** von 1. Mit einem Stride von 2 würden wir den Filter jeweils um 2 Pixel verschieben. Der Output (die Convolution) wäre dann nur halb so gross wie das Bild (hier also $6 \\times 6$ Pixel).\n\n::: {.callout-note}\n## Schlüsselschritt\n\nUnd nun der Schlüsselschritt im Verständnis: im obigen Beispiel waren die Werte des Filters (bzw. der Matrix) gegeben. In einem CNN werden die **Werte des Filters jedoch automatisch via Backpropagation gelernt**. Das CNN lernt also automatisch, auf welche Muster die Filter in den Convolution Layers achten sollen bzw. welche Muster besonders wertvoll sind, um gute Vorhersagen zu machen. Aus meiner Sicht ist das die Magie von CNNs.\n:::\n\n#### Convolution für Farbbilder\n\nIm Fall von Farbbildern ist das ganze etwas komplexer. In dem Fall hat jeder Convolution Filter **drei (Filter-)Matrizen** (mit potentiell anderen Gewichten), eine pro Farbchannel. Die Convolution findet dann für jeden Channel separat statt und am Schluss werden die drei resultierenden Convolutions wieder **übereinandergelegt** und **pixelweise summiert**, so dass jeder Convolution Filter lediglich einen zweidimensionalen Output ausgibt. Ganz am Schluss eines Convolution Layers wird auf jedem Pixel des zweidimensionalen Outputs noch die **Aktivierungsfunktion ReLU** angewendet.\n\nWie bereits erwähnt, hat ein Convolution Layer typischerweise **mehrere Filter**, die alle unterschiedliche Muster erkennen können. Ganz allgemein sagen wir, dass ein Convolution Layer $K$ Filter hat. Der finale Output jedes Filteres wird dann **Feature Map** genannt. Das heisst, ein Convolution Layer mit $K$ Filtern führt zu $K$ Feature Maps. Dieser Vorgang ist in folgender Abbildung dargestellt:\n\n![Ein vollständiger Convolution Layer für Farbbilder. Ein Layer hat insgesamt $K$ Filter und jeder Filter besteht aus drei Filtermatrizen. So resultieren $K$ Feature Maps.](images/convolutionLayer.png){width=90% #fig-convlayer}\n\nÜberlegen wir uns kurz, wie viele Parameter (Gewichte) dieser Convolution Layer hat. Jeder der $K$ Filter hat *drei* $3 \\times 3$ Matrizen, d.h. jeder Filter hat insgesamt 27 Parameter^[$3^3 = 27$], plus einen Bias Term pro Filter. Daraus folgt, dass ein Convolution Layer in unserem Beispiel insgesamt $(27 + 1) \\cdot K$ Parameter hat. Das sind in der Regel wesentlich weniger Parameter als wenn wir ein reguläres ANN verwenden würden, um das Problem zu lösen.\n\n#### ANN vs. CNN\n\nUm uns den Unterschied zwischen klassischen ANN und CNN noch klarer zu vergegenwärtigen, gehen wir kurz zum vereinfachten MNIST Beispiel zurück. Folgende Abbildung zeigt, was in einem ANN und einem CNN mit dem $12 \\times 12$ Bild einer handgeschriebenen \"7\" passiert:\n\n![Architektur eines ANNs vs. Convolution in einem CNN.](images/ann_vs_cnn.png){width=90% #fig-anncnn}\n\nFür das ANN (oberer Teil der Abbildung) werden die Pixel in einen 1D Input Layer *geflatted*. Der zentrale Punkt ist, dass danach **jedes Pixel** aus dem Input Layer mit **jedem Neuron** im Hidden Layer durch ein Gewicht verbunden ist. Für grosse Bilder (z.B. $1000 \\times 1000$ Pixel) ist diese Architektur nicht mehr rechenbar.\n\nDieses Problem wird durch CNNs gelöst (unterer Teil der Abbildung). Das Bild wird im Originalformat (im Fall eines Grayscale Bilds ist das 2D) im Input Layer dargestellt. Jeder **Feature Map** im Convolution Layer ist dann ebenfalls zweidimensional, alle Feature Maps zusammen sind dann aber ein 3D Konstrukt (gestapelte Matrizen). Jedes Pixel in einem Feature Map ist in einem gewissen Sinn ein Neuron. Der zentrale Punkt hier ist, dass jedes Pixel (Neuron) in einem Feature Map **nur mit 9 Pixels** im Input Layer verbunden ist und darum die **Konnektivität** im Netzwerk sehr **lokal** ist. Ausserdem verwendet jedes Pixel (Neuron) in einem Feature Map denselben Filter und darum die selben Parameter. Dies wird oft als **Weight Sharing** bezeichnet. Die lokale Konnektivität und das Weight Sharing begrenzen die Anzahl Gewichte im Vergleich zu einem klassischen ANN massiv.\n\n### Pooling Layers\n\nNach einem Convolutional Layer kommt in einem CNN oft ein sogenannter **Pooling Layer**. Die Funktionsweise dieser Art von Layer ist glücklicherweise viel einfacher als diejenige des Convolution Layers.\n\nIn den allermeisten Fällen wird heutzutage ein sogenanntes **Max-Pooling** angewendet. Dabei wird ganz einfach ein $2 \\times 2$ Quadrat über die Outputs eines Convolution Filters (also die Feature Maps) geschoben. Für jeden nicht-überlappenden $2 \\times 2$ Pixelblock wird der maximale Pixelwert in den Pooling Layer übernommen. Am besten schaut wir uns dazu das Beispiel in unten stehender Abbildung an:\n\n![Links: Originales MNIST Bild. Mitte: Output eines Convolution Layers (1 Feature Map). Rechts: Output eines Pooling Layers.](images/pooling.png){width=90% #fig-pooling}\n\nGanz wichtig: Indem wir Max-Pooling mit einem $2 \\times 2$ Quadrat betreiben, **reduzieren** wir jeden Feature Map **in beide Richtungen** um den **Faktor 2**. Der Pooling Layer reduziert also jeden Feature Map von $12 \\times 12$ zu $6 \\times 6$.\n\nDie Alternative zu Max-Pooling wäre **Mean-Pooling**, wo für jeden $2 \\times 2$ Pixelblock der Mittelwert über die vier Pixel gerechnet und in den Pooling Layer übernommen wird.\n\nEin Pooling Layer erfüllt viele verschiedene Zwecke:\n\n* Er reduziert die **Anzahl Berechnungen** sowie die **Auslastung des Arbeitsspeichers** (RAM). In obigem Beispiel haben wir gesehen, dass sich die Pixels bzw. Neurons in einem Feature Map um den Faktor 4 von 144 auf 36 verringern.\n* Er soll (durch *Downsampling*) das **Overfitting** bekämpfen.\n* Er führt zu einer sogenannten **Location Invariance**, d.h., ob zum Beispiel eine horizontale Linie in der zweiten, dritten oder vierten Zeile von Pixels liegt, soll keine Rolle spielen und dementsprechend soll ein möglichst ähnliches Signal an den nächsten Layer weiter gegeben werden.\n\n### Architektur\n\nWie eine **vereinfachte Architektur** eines CNNs aussieht, zeigt folgende Abbildung:\n\n<!-- ![Bla.](images/architektur.PNG){width=80% #fig-archit} -->\n\nIhr seht, dass ein CNN typischerweise mehrere Abfolgen von Convolution und Pooling Layers enthält. Wir sehen im ersten Convolution Layer **5 Feature Maps**, d.h. wir haben hier $K=5$ Filter angewendet und jeder Filter bestand aus drei kleinen Matrizen (z.B. $3\\times 3$). Danach folgt bereits ein erster Pooling Layer, der die 5 Feature Maps kleiner macht. Danach kommt ein zweiter Convolution Layer, der zu **10 Feature Maps** führt, d.h. wir haben hier $K=10$ Filter angewendet. **Ganz wichtig**: jeder der 10 Filter besteht in diesem Schritt aus **5** kleinen Matrizen (z.B. $3\\times 3$). Warum? Weil jeder Filter 5 Feature Maps aus dem vorherigen Layer verarbeiten muss. Danach folgt ein zweiter Pooling Layer, der die 10 Feature Maps verkleinert. Wir können beobachten, dass die Feature Maps durch das Pooling stets etwas kleiner werden. Dafür erhöhen wir grundsätzlich die *Anzahl* Feature Maps von Layer zu Layer, indem wir in jedem Convolution Layer die Anzahl Filter $K$ erhöhen. In unserem Beispiel haben wir $K$ vom ersten zum zweiten Convolution Layer von 5 auf 10 erhöht.\n\nNach diesen zwei Convolution-Pooling Sequenzen wird der letzte Pooling Output *geflatted* und es folgen noch ein paar **dense (fully connected) Layers** wie wir sie aus einer klassischen ANN Architektur kennen. Und ganz am Schluss kommt der Output Layer, welcher in Bildklassifikationsproblemen meist ein **Softmax** Layer ist, da wir versuchen ein Bild in eine von z.B. 7 Kategorien zu klassifizieren (z.B. Vogel, Haus, Baum, Person, etc.).\n\nDie Architektur eines CNNs sowie die Ausgestaltung der einzelnen Layers ist enorm flexibel und es gibt **unzählige Hyperparameter**:\n\n* Anzahl Convolution Layers\n* Anzahl Pooling Layers\n* Stride\n* Dimensionen der Convolution Filter\n* Zero-Padding: ja oder nein\n* Max- oder Mean-Pooling\n* Viele weitere\n\n### Data Augmentation\n\nEine Technik, welche CNNs massiv verbessert hat, ist **Data Augmentation**. Bei dieser Technik werden die Bilder während des Trainings leicht verändert. Zum Beispiel kann ein gegebenes Bild leicht verschoben oder rotiert, einen Ausschnitt daraus gewählt oder die Lichtbedingungen verändert werden. Ein Beispiel seht ihr in folgender Abbildung (Quelle: TseKiChung via Wikimedia):\n\n![Quelle der Abbildung: TseKiChung, via Wikimedia Commons, CC BY-SA 4.0](images/data_aug.png){width=70% #fig-dataaugment}\n\nData Augmentation wirkt wie **Regularisierung** und kann das Overfitting von CNNs wesentlich eindämmen. Ein weiterer toller Aspekt von Data Augmentation ist, dass die Veränderungen der Bilder **on the fly** während des Modelltrainings gemacht werden können und die veränderten Bilder nicht abgespeichert werden müssen. Mit Keras und TensorFlow können wir direkt nach dem Input Layer spezielle Layers ins Modell aufnehmen, die solche Data Augmentation Schritte für uns durchführen. Details dazu findet ihr [hier](https://tensorflow.rstudio.com/examples/image_classification_from_scratch.html#using-image-data-augmentation).\n\n## Beispiel: ResNet\n\nWir schauen uns hier die Architektur des Modells **ResNet34** an, das im Jahr 2015 von Microsoft Mitarbeitenden vorgeschlagen wurde ([He et al., 2015](https://arxiv.org/abs/1512.03385)). Eine Variante dieses Modells hat 2015 die sogenannte ImageNet Challenge gewonnen (dazu später mehr).\n\nDer Name ResNet34 ist dadurch begründet, dass **Skip Connections** verwendet werden und dadurch **Residuen (Res)** gelernt werden (ähnlich wie Gradient Boosting). Was Skip Connections genau sind, sehen wir etwas weiter unten. Ausserdem hat das Modell 34 Layers, wobei die Pooling Layers nicht mitgezählt werden.\n\nDie Architektur des ResNet34 sieht wie folgt aus:\n\n![Quelle der Abbildung: [He et al., 2015](https://arxiv.org/abs/1512.03385)](images/resnet34.png){width=100% #fig-resnet34}\n\nSchauen wir uns die einzelnen Komponenten schrittweise (von links nach rechts) an:\n\n* Als Input erwartet das Modell Farbbilder mit einer Auflösung von $224\\times 224$ Pixels (mit 3 Farbchannels).\n* Im ersten Convolution Layer (orange) werden $K=64$ Filter der Grösse $7\\times 7$ verwendet. Weil wir einen **Stride von 2** (in der Abbildung gekennzeichnet durch \"/2\") verwenden (die Filter also immer um 2 und nicht nur um 1 Pixel verschieben), reduzieren wir die Input Bilder um die Hälfte. Die 64 resultierenden Feature Maps haben also je eine Grösse von $112\\times 112$ Pixels.\n* Danach folgt ein Max. Pooling Layer, ebenfalls mit einem Stride von 2, so dass die Dimensionen der 64 Feature Maps nochmal halbiert werden auf $56\\times 56$ Pixels.\n* Nun folgen **6 Convolution Layers** (violett). Jeder Layer hat $K=64$ Filter der Grösse $3\\times 3$ und einem Stride von 1, was bedeutet, dass die Dimensionen der resultierenden Feature Maps im Moment nicht halbiert werden. Der zentrale Aspekt dieser Architektur sind die Pfeile oberhalb der Layers. Sie stellen die **Skip Connections** dar. Der erste solche Pfeil bedeutet, dass der Output aus dem Pooling Layer nicht nur in den ersten violetten Convolution Layer einfliesst, sondern auch direkt in den dritten violetten Layer. Der Output des Pooling Layers kann also auch gewisse Layer überspringen (*skippen*). Solche Skip Connections haben viele Vorteile. Zum Beispiel \"fliessen\" die wesentlichen Informationen so schneller durch das Modell und das Training des Modells wird kürzer. Was in der Abbildung nicht dargestellt ist: in jedem Convolution Layer wird nach der Convolution, eine Batch Normalization (d.h. Standardizierung der Outputs) betrieben bevor die Outputs noch durch die ReLU Aktivierungsfunktion fliessen.\n* Es folgen **8 weitere Convolution Layers** (grün), in denen jeweils $K=128$ Filter der Grösse $3\\times 3$ verwendet werden. Um die Architektur ausgeglichen zu halten, wird im ersten grünen Convolution Layer ein Stride von 2 verwendet, wodurch sich die Dimensionen der Feature Maps auf $28\\times 28$ Pixels reduzieren. Das stellt jedoch ein Problem für die Skip Connection dar. Der Output aus dem letzten violetten Convolution Layer enthält 64 Feature Maps der Grösse $56\\times 56$ und soll nun nach den ersten beiden grünen Convolution Layers hinzu addiert werden. Der dazugehörige **gestrichelte** Pfeil stellt dar, dass bei dieser Skip Connection der Output aus dem letzten violetten Layer angepasst wird, so dass er ebenfalls 128 Feature Maps der Grösse $28\\times 28$ entspricht.\n* Nun folgen **12 weitere Convolution Layers** (rot), in denen jeweils $K=256$ Filter der Grösse $3\\times 3$ verwendet werden. Auch hier haben die Filter des ersten Layers der roten Gruppe einen Stride von 2, wodurch die Dimensionen der Feature Maps auf $14\\times 14$ reduziert werden. Dadurch muss auch hier die erste Skip Connection entsprechend angepasst werden.\n* Danach folgt die letzte Gruppe von **6 Convolution Layers** (blau), in denen jeweils $K=512$ Filter der Grösse $3\\times 3$ verwendet werden. Durch den Stride von 2 im ersten Layer der Gruppe reduziert sich die Grösse der Feature Maps auf nur noch $7\\times 7$.\n* Nun kommt ein **Global Average Pooling** Layer, der für jeden der resultierenden 512 Feature Maps des letzten Convolution Layers den Mittelwert über die $7\\times 7 = 49$ Pixels rechnet.\n* Die resultierenden 512 Mittelwerte sind **fully connected** mit den 1000 Output Neurons. Letztere sind nötig, weil die ImageNet Challenge 1000 mögliche Kategorien hat. Die 1000 Outputs der Output Neurons werden mittels **Softmax** in Wahrscheinlichkeiten umgerechnet.\n\nWow! Ziemlich komplex das Ganze, aber die einzelnen Komponenten sind eigentlich erstaunlich simpel.\n\n\n\n## Anwenden von Modellen\n\nEs gibt viele verschiedene Möglichkeiten, wie ihr Deep Learning Modelle anwenden könnt. Die verschiedenen Möglichkeiten unterscheiden sich im Grad der technischen Komplexität und hängen davon ab, ob eine bestehende Lösung euer konkretes Problem bereits vollumfänglich abbildet. Konkret gibt es folgende Möglichkeiten:\n\n1. Ihr verwendet ein Deep Learning Modell über **API-Services**, welche oft von grossen Firmen wie Amazon, Google oder OpenAI angeboten werden. Das ist sehr einfach, hat jedoch den Nachteil, dass ihr keinerlei Flexibilität habt und das Modell nicht verändern könnt. Ausserdem sind solche Dienstleistungen in den meisten Fällen kostenpflichtig.\n2. Wie weiter unten demonstriert, könnt ihr **bestehende (trainierte) Modelle** (vor allem CNNs) auch direkt mit Keras herunterladen und verwenden. Dabei habt ihr vollen Einblick in das Modell und allzu schwierig ist es dank Keras auch nicht. Für mobile Applikationen enthält Keras sogar sogenannte *Lightweight Models* ([MobileNet](https://tensorflow.rstudio.com/reference/keras/application_mobilenet_v2.html)).\n3. Wenn es für euer Problem, das ihr lösen wollt, keine vorgefertigte Lösung gibt (zum Beispiel wenn ihr andere Kategorien als die ImageNet Kategorien vorhersagen wollt), dann könnt ihr ein bestehendes (CNN) Modell nehmen und nur die letzten paar Layers trainieren. Dieser Prozess wird **Transfer Learning** genannt und ist enorm hilfreich. Die Convolution Layers von grossen Modellen, die von Google, Microsoft, etc. trainiert wurden, eignen sich oft auch für andere Probleme. Eine Anleitung für das Transfer Learning findet ihr [hier](https://tensorflow.rstudio.com/guides/keras/transfer_learning.html).\n4. *Last but not least* könnt ihr natürlich auch ein **eigenes Modell von Grund auf trainieren**. Doch dazu braucht ihr erst einmal einen sehr grossen und vor allem **gelabelten** Datensatz. Für das Labelling greifen die Entwicklerinnen und Entwickler von DL Modellen oft auf Crowdsourcing Plattformen wie z.B. AmazonTurk zurück. Wie das Trainieren eines eigenen CNNs funktioniert, ist in diesem [Tutorial](https://tensorflow.rstudio.com/examples/cifar10_cnn) oder in HOML (für Python) beschrieben. Für realistische Modelle empfehle ich euch, eine Cloud Lösung zu verwenden (z.B. [Google Colab](https://colab.research.google.com/)), denn unsere Rechner haben grundsätzlich zu wenig Processing Power und vor allem auch zu wenig Arbeitsspeicher (RAM), ausser ihr habt eine **Graphics Processing Unit** (GPU) und ganz viel RAM. Wie ihr lokal mit R eine GPU einbindet, ist [hier](https://tensorflow.rstudio.com/install/local_gpu) beschrieben.\n\n### Anwenden eines bestehenden CNNs (Option 2)\n\nWir schauen uns hier ein bestehendes CNN an, das mit den Daten aus der [ImageNet Challenge](https://www.image-net.org/index.php) trainiert wurde. Der entsprechende Datensatz enthält über 14 Millionen Bilder, welche alle **gelabelt** sind. Jedes Bild muss in eine von 1000 Kategorien klassifiziert werden. Die möglichen Kategorien findet ihr [hier](https://gist.github.com/yrevar/942d3a0ac09ec9e5eb3a). Die Performance wird mit der **Top-5 Error Rate** gemessen, d.h. eine Vorhersage entspricht nur dann einem Fehler, wenn das wahre Label nicht unter den Top-5 Vorhersagen des Modells ist. Das aktuell beste Modell hat eine Top-5 Error Rate von etwas mehr als 2%. Wow!\n\nWir werden hier das **ResNet50** Modell verwenden. Eine Variante davon hat die 2015 ImageNet Challenge gewonnen mit einer Top-5 Error Rate von weniger als 3.6% (vgl. HOML, p. 505). Wir haben uns im vorherigen Kapitel bereits die Architektur des etwas kleineren Modells **ResNet34** angeschaut.\n\nAls erstes laden wir das trainierte Modell mit Keras. Dazu verwenden wir die Funktion `application_resnet50()`. Wir kriegen das Modell mit den optimalen Gewichten, indem wir das Argument `weights = \"imagenet\"` setzen. Mit der `summary()` Funktion können wir uns die Architektur des Modells anschauen:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Packages laden\nlibrary(tidyverse)\nlibrary(tensorflow)\nlibrary(keras)\nlibrary(jpeg)\n\n# Als erstes laden wir das resnet50 Model und zwar mit den optimalen Gewichten.\nmodel <- application_resnet50(weights = \"imagenet\")\n\n# Schauen wir uns die Architektur dieses Modells mal an.\nsummary(model)\n```\n:::\n\n\n```\nModel: \"resnet50\"\n__________________________________________________________________________________________________\nLayer (type)                           Output Shape               Param #        Connected to                            \n==================================================================================================\ninput_1 (InputLayer)                   [(None, 224, 224, 3)]      0                                                      \n__________________________________________________________________________________________________\nconv1_pad (ZeroPadding2D)              (None, 230, 230, 3)        0              input_1[0][0]                           \n__________________________________________________________________________________________________\nconv1_conv (Conv2D)                    (None, 112, 112, 64)       9472           conv1_pad[0][0]                         \n__________________________________________________________________________________________________\nconv1_bn (BatchNormalization)          (None, 112, 112, 64)       256            conv1_conv[0][0]                        \n__________________________________________________________________________________________________\nconv1_relu (Activation)                (None, 112, 112, 64)       0              conv1_bn[0][0]                          \n__________________________________________________________________________________________________\npool1_pad (ZeroPadding2D)              (None, 114, 114, 64)       0              conv1_relu[0][0]                        \n__________________________________________________________________________________________________\npool1_pool (MaxPooling2D)              (None, 56, 56, 64)         0              pool1_pad[0][0]                         \n__________________________________________________________________________________________________\n\n...\n\n_______________________________________________________________________________________________________\navg_pool (GlobalAveragePooling2D)      (None, 2048)               0              conv5_block3_out[0][0]                  \n_______________________________________________________________________________________________________\nprobs (Dense)                          (None, 1000)               2049000        avg_pool[0][0]                          \n=======================================================================================================\nTotal params: 25,636,712\nTrainable params: 25,583,592\nNon-trainable params: 53,120\n_______________________________________________________________________________________________________\n```\nDie Architektur des Modells ist riesig, weshalb ich sie hier verkürzt dargestellt habe. Ihr seht beim **Input Layer**, dass das Modell Farbbilder (3 Channels) mit einer Auflösung von **224 x 224 Pixel** erwartet. Nach dem Input Layer kommt der **erste Convolutional Layer** (= oranger Layer in ResNet34 Architektur). In Keras bzw. TensorFlow werden die **einzelnen Elemente** eines Convolution Layers separat dargestellt. Der erste Layer setzt sich zusammen aus:\n\n* `conv1_pad (ZeroPadding2D)`: In einem ersten Schritt wird das Zero Padding gemacht und da brauchen wir selbstverständlich keine Gewichte dazu. \n* `conv1_conv (Conv2D)`: Dann kommen 64 (7 x 7) Convolution Filters. Überlegen wir uns doch kurz, wie wir auf die insgesamt 9472 Gewichte kommen. Wir haben 64 Filter, wovon jeder drei 7 x 7 Matrizen enthält. Warum drei? Weil wir pro Farbchannel eine separate 7 x 7 Matrix haben. Das gibt uns bereits $64 \\cdot 3 \\cdot 7 \\cdot 7 = 9408$ Gewichte. Dazu kommen noch 64 Bias Terms, was uns dann insgesamt $9408 + 64 = 9472$ Gewichte gibt.\n* `conv1_bn (BatchNormalization)`: Danach kommt eine sogenannte **Batch Normalization**, was vereinfacht nichts anderes als eine Standardisierung der Outputs der Convolution Filters ist.\n* `conv1_relu (Activation) `: ReLU Aktivierung der standardisierten Outputs in den 64 Feature Maps.\n\nDanach folgt der Max. Pooling Layer, welcher in Keras bzw. TensorFlow ebenfalls in zwei Unterschritte aufgeteilt wird: `pool1_pad (ZeroPadding2D)` und `pool1_pool (MaxPooling2D)`. Nicht abgebildet werden die diversen Gruppen von Convolution Layers.\n\nDer Output Layer ist **dense** und enthält 1000 Neurons, da wir die Wahrscheinlichkeiten für 1000 Kategorien rechnen wollen. Der zweitletzte Global Average Pooling Layer hat 2048 Neurons (in ResNet34 hatten wir hier nur 512 Neurons), wodurch der Output Layer insgesamt $(2048 + 1) \\cdot 1000 = 2'049'000$ Gewichte hat. Ganz unten im Output ist ersichtlich, dass das Modell insgesamt über 25 Millionen Parameter hat, wovon die meisten trainiert werden müssten. Hier haben wir aber die bereits trainierten (optimalen) Gewichte importieren können.\n\nNun extrahieren wir die Gewichte aus dem Modell und schauen uns den **ersten Filter** im **ersten Convolutional Layer** an. Anhand des Indexings, `[ , , , 1]`, seht ihr, dass die Gewichte in einem 4-dimensionalen Array gespeichert sind. Die ersten beiden Dimensionen bezeichnen die Dimensionen der Filtermatrizen (also 7 x 7). Die dritte Dimension bezeichnet die Anzahl Feature Maps, welche der Convolutional Layer aus dem vorherigen Layer erwartet. In unserem Fall sind das 3, da wir im ersten Convolutional Layer die drei Farbchannels aus dem Input Layer erhalten. Die vierte Dimension bezeichnet die Anzahl Filter des vorliegenden Convolutional Layers. Mit der `1` spezifizieren wir, dass wir nur den ersten Filter anschauen wollen.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Wir können auch die Gewichte extrahieren.\noptimal_weights <- model %>% get_weights()\n\n# Erster Convolution Filter im ersten Conv. Layer\noptimal_weights[[1]][ , , , 1]\n```\n:::\n\n\n```\n, , 1\n\n             [,1]        [,2]         [,3]         [,4]        [,5]        [,6]        [,7]\n[1,]  0.028252628  0.01818723  0.015884932  0.002420052 -0.05301533 -0.04735583  0.01854295\n[2,]  0.007990093  0.02488567  0.076726004  0.090264283 -0.01891512 -0.07935619 -0.01536172\n[3,] -0.027473288 -0.06575351  0.019992139  0.184763417  0.11552856 -0.08998038 -0.09464549\n[4,] -0.009787651 -0.07923734 -0.129819512  0.095235661  0.27007112  0.09940726 -0.01493159\n[5,]  0.023180470 -0.04645163 -0.183006614 -0.156041548  0.05361670  0.08349565  0.03695760\n[6,]  0.042254806  0.04594706 -0.046616178 -0.127040774 -0.02102392  0.03322218  0.02505229\n[7,]  0.014630316  0.03523030  0.004108737 -0.060385078 -0.01716923  0.01151425  0.00479147\n\n, , 2\n\n             [,1]        [,2]        [,3]        [,4]        [,5]         [,6]        [,7]\n[1,]  0.005868278  0.01875543  0.03614214  0.01715494 -0.09355789 -0.124100089 -0.02680790\n[2,] -0.007687946  0.02429662  0.14944476  0.21562344  0.01338885 -0.176872283 -0.12294715\n[3,] -0.074660495 -0.15249401  0.06102424  0.41499856  0.33233449 -0.081507459 -0.21111147\n[4,] -0.054444715 -0.25528842 -0.26442963  0.21033862  0.57014650  0.277241141 -0.02648117\n[5,]  0.023048820 -0.17785294 -0.41178319 -0.26845443  0.18579270  0.250555605  0.09637067\n[6,]  0.097701266  0.03894836 -0.19233614 -0.29224005 -0.03729927  0.099565394  0.10021943\n[7,]  0.061221115  0.06344386 -0.02231540 -0.17049119 -0.08630268  0.007418274  0.02751930\n\n, , 3\n\n              [,1]        [,2]        [,3]         [,4]          [,5]        [,6]        [,7]\n[1,] -0.0024409075  0.01904538  0.02179598 -0.003380956 -0.0769589692 -0.07131131  0.01439408\n[2,]  0.0003704716  0.02912742  0.11718027  0.150795683 -0.0093867844 -0.13021459 -0.07923260\n[3,] -0.0334048420 -0.08807442  0.08053155  0.324004412  0.2164803147 -0.09732457 -0.17507587\n[4,] -0.0174925867 -0.15134996 -0.18083088  0.167103648  0.4065239429  0.16355224 -0.07702903\n[5,]  0.0203978457 -0.10906302 -0.27673617 -0.172197968  0.1320384443  0.14969076  0.02951569\n[6,]  0.0638262108  0.04572181 -0.11566665 -0.178826123  0.0007846743  0.06553538  0.06971015\n[7,]  0.0186353922  0.03358492 -0.02011830 -0.127520546 -0.0607556999  0.00784576  0.02711843\n```\n\nWie erwartet besteht der erste Filter aus **drei 7 x 7 Matrizen**.\n\nWir laden nun das Bild des Zebras mit der Funktion `image_load()` und lassen es durch die Funktion gleich in die korrekte Auflösung überführen. Wir erinnern uns, dass *ResNet50* Bilder mit einer Auflösung von 224 x 224 Pixels erwartet. Danach konvertieren wir das Bild in einen 3D-Array:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Lade ein Bild mit 'image_load()'\n# Wichtig: resnet50 erwartet eine Auflösung von 224 x 224 Pixels\nimg <- image_load(\"zebra.jpg\", target_size = c(224, 224))\n\n# Wir konvertieren das Bild in einen 3D-Array (letzte Dimension sind die drei Farbchannels)\nx <- image_to_array(img)\n```\n:::\n\n\nWir können das Bild mit geringerer Auflösung nochmals plotten:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Quadratischer Plot in R\npar(pty = \"s\")\n\n# Leere Plot-Hülle\nplot(0:1, 0:1, type = \"n\", ann = FALSE, axes = FALSE)\n\n# Bild plotten\nrasterImage(x / 255, 0, 0, 1, 1)\n```\n:::\n\n\n<!-- ![Bla.](images/zebra_224_224.jpeg){width=60% #fig-zebra} -->\n\nNun verändern wir die Dimensionalität des Bilds in einen 4-D Array. Warum wir das tun, ist im Code Kommentar unten beschrieben.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Hier müssen wir noch eine vierte Dimension voranstellen.\n# Diese Dimension bezeichnet die Batchgrösse. Da wir hier\n# nur für ein Bild eine Vorhersage machen wollen, hat diese\n# Dimension den Wert 1.\nx <- array_reshape(x, c(1, dim(x)))\n```\n:::\n\n\nDie Funktion `imagenet_preprocess_input()` enthält alle notwendigen Preprocessing Schritte, welche das Modell erwartet.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Und nun noch ein paar spezifischen Preprocessing Schritte,\n# welche in der Funktion 'imagenet_preprocess_input()' def. sind.\nx <- imagenet_preprocess_input(x)\n```\n:::\n\n\nNun können wir die Vorhersage des Modells für unser Bild `x` rechnen und die Top-5 Vorhersagen ausgeben lassen.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Nun rechnen wir die Vorhersage\npreds <- model %>% predict(x)\n\n# Schöner Output\nimagenet_decode_predictions(preds, top = 5)[[1]]\n```\n:::\n\n\n```\n  class_name class_description        score\n1  n02391049             zebra 9.998761e-01\n2  n02129604             tiger 2.369525e-05\n3  n02422699            impala 1.781611e-05\n4  n02422106        hartebeest 1.060396e-05\n5  n02123159         tiger_cat 8.302844e-06\n```\n\nDas Modell hat kein Problem, das Bild korrekt zu klassifizieren! Doch was passiert eigentlich in all diesen Convolution Layers? Der folgende [Blogpost](https://machinelearningmastery.com/how-to-visualize-filters-and-feature-maps-in-convolutional-neural-networks/) zeigt die Outputs der Convolutions Layers für eine andere bekannte CNN Architektur, nämlich VGG16.\n\nIm Bereich Computer Vision gibt es viele verschiedene Probleme. Das Hauptproblem ist die Klassifikation eines Objekts in einem Bild - das Problem, das wir bis jetzt betrachtet haben. Andere Probleme sind die **gleichzeitige Klassifikation und Lokalisation** eines Objekts in einem Bild, die Erkennung von **mehreren Objekten** in einem Bild oder die **Klassifikation jedes Pixels** in einem Bild. All diese Varianten des Standard Computer Vision Problems sind in [@Geron, Kapitel 14] im Detail beschrieben.\n",
    "supporting": [
      "09_cnn_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}