{
  "hash": "30453302bdc35abca82f57963cb2d69d",
  "result": {
    "engine": "knitr",
    "markdown": "# Ensembles {#sec-ensemble}\n\nEin Ensemble Modell ist ein Modell, das auf vielen verschiedenen **individuellen Regressions- oder Klassifikationsmodellen** aufbaut, also ein Ensemble von individuellen Modellen. Der Grossteil der Ensemble Modelle verwendet als individuelle Modelle **Entscheidungsbäume**. Konkret heisst das, dass die Vorhersagen der individuellen Entscheidungsbäume in geeigneter Form **aggregiert** werden. Eine schöne Analogie für Ensemble Methoden ist das Konzept **Wisdom of the Crowd**: wir kombinieren das \"Wissen\" von vielen verschiedenen Modellen zu einem starken Ensemble.\n\nDer Vorteil von diesem Vorgehen ist, dass Ensemble Modelle oft (viel) bessere Vorhersagen machen als ein individueller Entscheidungsbaum. Tatsächlich ist es so, dass Ensemble Modelle sogar dann gut funktionieren, wenn die individuellen Modelle des Ensembles nur leicht bessere Vorhersagen als der Zufall machen. Man spricht darum manchmal von Ensembles von **Weak Lerners**.\n\nEnsemble Modelle sind (neben Modellen aus dem Deep Learning) die wettbewerbsfähigsten Modelle in der Praxis. Der Nachteil ist, dass wir mit Ensemble Modellen stärker in den Bereich von **Black-Box** Modellen vorrücken. Das heisst, es wird nun schwieriger, die Einflüsse der Input-Variablen auf unsere Zielvariable genau zu verstehen.\n\nDoch warum funktionieren Ensembles so gut? Hier hilft eine Analogie zur **klassischen Statistik**, die in [@islr, Kapitel 8] gut dargelegt wird. Wir nehmen an, wir haben eine Stichprobe von $n$ Beobachtungen (z.B. Hauspreise).\n\n* Die Standardabweichung $\\hat{\\sigma}$ besagt, wie stark eine einzelne Beobachtung im Schnitt vom Stichprobenmittelwert abweicht.\n* Der Standardfehler des Mittelwerts $\\frac{\\hat{\\sigma}}{\\sqrt{n}}$ besagt, wie stark der Stichprobenmittelwert im Schnitt vom wahren (unbekannten) Populationsmittelwert abweicht.\n\nDie Standardabweichung $\\hat{\\sigma}$ sagt also etwas über die Streuung von einzelnen Beobachtungen aus, während der Standardfehler des Mittelwerts etwas über die Streuung des Mittelwerts aussagt. Durch das **Mitteln** (Berechnung des Mittelwerts) wird die Streuung (Varianz) um den Faktor $1/\\sqrt{n}$ reduziert. Bei Ensemble Modellen passiert etwas ähnliches: indem wir die Vorhersagen von vielen individuellen Modellen **mitteln**, reduziert sich die **Varianz**, während der Bias nicht wesentlich ansteigen sollte. Basierend auf dem Bias-Variance Tradeoff können wir ableiten, dass ein Ensemble Modell mit geringerer Varianz auch zu besseren Vorhersagen führen sollte.\n\n::: {.callout-note}\n## Voraussetzung für obiges Resultat\n\nDie Formel für den Standardfehler des Mittelwerts in der klassischen Statistik gilt nur, wenn die $n$ Beobachtungen in der Stichprobe unabhängig sind.\n\nAuch dieses Resultat lässt sich auf Ensemble Modelle übertragen: **je unabhängiger** die individuellen Modelle voneinander sind, **desto stärker** ist die Reduktion in der Varianz und desto besser die Vorhersagen des Ensembles.\n:::\n\nEine ganz simple Form von Ensembles sind sogenannnte **Voting Modelle**. In vielen Projekten trainieren wir mehrere Modelle und entscheiden uns dann für das beste Modell. Doch warum nicht alle trainierten Modelle verwenden? Genau das ist die Idee von Voting Modellen. Die Idee könnte simpler nicht sein: wir lassen jedes unserer Modelle eine Vorhersage machen (*hard* oder *soft*) und kombinieren die individuellen Vorhersagen zu einer aggregierten Vorhersage. Das Prinzip eines solchen Modells ist in folgender Abbildung anhand des Spam Filters illustriert:\n\n![Die Idee von Voting Modellen anhand des Spam Filter Problems.](images/VotingClassifier.png){width=60% #fig-votingclassifier}\n\nAuch dieses Kapitel ist teilweise inspiriert durch [@islr, Kapitel 8] und [@Geron, Kapitel 7].\n\n## Bagging\n\nWir haben in der Einführung bereits gelernt, dass ein Ensemble vor allem dann gut funktioniert, wenn die individuellen Modelle, über die aggregiert wird, **möglichst unabhängig** sind. Es gibt beispielsweise folgende zwei Wege, wie wir versuchen, möglichst viel Unabhängigkeit zwischen den individuellen Modellen herzustellen:\n\n1. Wir rechnen effektiv unterschiedliche Modelle wie beim Voting Modell oben gesehen.\n2. Wir rechnen jedes mal dasselbe Modell, aber stets auf einem anderen Subset des Trainingsdatensatzes.\n\nEin Ansatz nach zweitem Muster ist das sogenannte **Bootstrap Aggregating** (Bagging). Beim Bagging generieren wir eine grosse Anzahl $B$ **verschiedener Subsets** aus dem Trainingsdatensatz und lernen für jedes Subset einen Entscheidungsbaum. Jeder so trainierte Baum wird anders aussehen, da sie alle auf unterschiedlichen Trainingsdatensätzen trainiert wurden: nichts anderes als eine Manifestation der **hohen Varianz** individueller Bäume.\n\nDurch das Aggregieren der Vorhersagen dieser Bäume wird die Varianz des Ensembles aber substanziell kleiner sein. Im Idealfall resultieren so massiv bessere Vorhersagen des Ensembles. Bevor wir weitermachen, müssen wir uns zuerst mal überlegen, wie wir aus einem gegebenen Traininsdatensatz Subsets generieren.\n\n### Bootstrap\n\nFür die Generierung von unterschiedlichen Subsets des Trainingsdatensatzes wird beim Bagging eine altbekannte Technik aus der Statistik angewendet, nämlich der **Bootstrap**.\n\nBootstrapping wird in der klassischen Statistik angewendet, um die Unsicherheit einer Schätzung (d.h. deren Varianz oder Standardabweichung) zu berechnen, wenn es keine analytischen Lösung gibt um die Unsicherheit zu beziffern.\n\n::: {.callout-note}\n## Wie funktioniert Bootstrapping?\n\nBootstrapping ist im Prinzip eine besondere Art von **Sampling**: wir ziehen zufällig $n$ Beobachtungen aus einem Datensatz der Grösse $n$ **mit Zurücklegen**. Das Zurücklegen ist der zentrale Aspekt: dadurch werden gewisse Beobachtungen mehr als einmal in unserem Bootstrap Sample landen und gewisse Beobachtungen gar nicht. Nur so kriegen wir unterschiedliche Bootstrap Samples.\n\nTypischerweise ziehen wir insgesamt $B$ solche Bootstrap Samples (z.B. $B=1000$) und kriegen so viele **verschiedene Subsets** unseres Datensatzes. Jedes Subset hat haber gleich viele Beobachtungen ($n$) wie der Ursprungsdatensatz.\n:::\n\nAm besten lässt sich das Prinzip des Bootstrappings anhand eines einfachen Beispiels illustrieren. Wir haben folgende Stichprobe der Grösse $n=10$:\n\n$$\n\\{525, 1081, 784, 556, 612, 1563, 886, 978, 648, 1025\\}\n$$\nSie können sich vorstellen, dass es sich hier um die Gesamtausgaben von Kund:innen bei einem Onlinehändler handelt. Es ist hier problemlos möglich, die mittleren Ausgaben sowie den Standardfehler des Mittelwerts zu berechnen. \n\nDer Mittelwert ist $\\bar{x}=865.8$ und der Standardfehler des Mittelwerts $s_{\\bar{x}}$ kann selbstverständlich analytisch berechnet werden:\n\n$$\ns_{\\bar{x}}=\\frac{\\hat{\\sigma}}{\\sqrt{n}}=\\frac{316.47}{\\sqrt{10}}\\approx 100\n$$\n\nManchmal gibt es aber keine analytische Formel, um die Unsicherheit einer Schätzung zu beziffern. In diesen Fällen kann die Boostrap Technik enorm hilfreich sein. Die folgende Abbildung zeigt, wie wir den Standardfehler des Mittelwerts mithilfe des Bootstraps approximieren können:\n\n![Wir samplen hier 1000 Bootstrap Samples aus der ursprünglichen Stichprobe. Für jedes Bootstrap Sample können wir einen Mittelwert rechnen. So kriegen wir 1000 geschätzte Mittelwerte. Die Standardabweichung über diese 1000 Mittelwerte ist eine Schätzung für den Standardfehler des Mittelwerts. Die Farbkodierung der Bootstrap Samples zeigt, dass gewisse Elemente der ursprünglichen Stichprobe mehrmals in den Samples vorkommen.](images/Bootstrap2.PNG){width=90% #fig-boot2}\n\nMit $B=1000$ kriegen wir 1000 Bootstrap Samples. Für jedes Sample rechnen wir den geschätzten Mittelwert. Der Mittelwert über alle Mittelwerte ergibt ca. 870, aber das ist nicht, was uns hier primär interessiert. Die *Standardabweichung* über die 1000 Mittelwerte, die wir basierend auf den Bootstrap Samples rechnen, gibt uns eine Schätzung für den *Standardfehler des Mittelwerts*. Unsere Bootstrap Schätzung (95) ist nicht weit entfernt von der analytischen Lösung (100)!\n\nDas Bootstrapping ist übrigens ganz einfach in `R` umsetzbar:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Stichprobe\ndata <- c(525, 1081, 784, 556, 612, 1563, 886, 978, 648, 1025)\n\n# B festlegen\nB <- 1000\n\n# Seed für Reprodzierbarkeit des Samplings\nset.seed(123)\n\n# Bootstrap Sampling (bs enthält die 1000 geschätzten Mittelwerte)\nbs <- sapply(1:B, function(x) mean(sample(x = data, size = length(data), replace = TRUE)))\n\n# Approximation des Standardfehlers des Mittelwerts\nsd(bs)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 94.86101\n```\n\n\n:::\n:::\n\n\n### Modellspezifikation\n\nWir generieren also mit der Bootstrap Technik eine grosse Anzahl $B$ Subsets aus dem Trainingsdatensatz und rechnen für jedes Subset einen separaten Entscheidungsbaum. Beim Bagging beschränken wir die Bäume typischerweise *nicht* (keine max. Tiefe oder ähnliches). Jeder einzelne Baum wird darum viel Varianz, aber relativ wenig Bias haben.\n\nDie Idee des Ensembles ist nun, dass wir die $B$ Vorhersagen, die wir von all den individuellen Entscheidungsbäumen kriegen, aggregieren.\n\nIm Fall des **Regressionsproblems** rechnen wir ganz einfach den **Durchschnitt** über die $B$ Vorhersagen, oder mathematisch ausgedrückt:\n\n$$\n\\hat{f}(\\mathbf{x}_i) = \\frac{1}{B} \\sum_{b=1}^B \\hat{f}_b(\\mathbf{x}_i)\n$$\nwobei $\\hat{f}_b(\\mathbf{x}_i)$ die Vorhersage des Baums im $b$-ten Subset bezeichnet.\n\nIm Fall des **Klassifikationsproblems** können wir zwischen einem **Soft Vote** oder einem **Hard Vote** wählen:\n\n* Beim Soft Vote rechnen wir den Durchschnitt über die vorhergesagten Wahrscheinlichkeiten der $B$ Bäume.\n* Beim Hard Vote entscheiden wir uns für die \"hard prediction\", die unter den $B$ Bäumen am häufigsten vorkommt.\n\nFolgende Abbildung zeigt das Vorgehen schematisch anhand des `housingrents` Datensatzes, den Sie bereits von den Entscheidungsbäumen kennen. Es handelt sich hierbei um ein Regressionsproblem:\n\n![Bagging Ensemble mit $B=3$ Bäumen für das `housingrents` Problem. Für eine Testbeobachtung (Wohnung) mit einem ökonomischen Alter von 9 Jahren und einer Fläche von 95 Quadratmetern, die im Besitz der Firma NRE ist, wird durch unser Ensemble eine Miete von CHF 2'150 vorhergesagt.](images/Bagging.png){width=90% #fig-bagging}\n\nWir aggregieren hier der Einfachheit halber nur $B=3$ Bäume zu einem Bagging Ensemble.\n\n### Out-of-Bag Beobachtungen\n\nDas Bootstrap Sampling führt dazu, dass jedes Sample im Schnitt nur rund 2/3 der Beobachtungen im Trainingsdatensatz enthält. Oder in anderen Worten: nur rund 2/3 der Beobachtungen werden mindestens einmal gezogen. Die für ein gegebenes Bootstrap Sample nicht gezogenen Beobachtungen nennen wir die **Out-of-Bag** (OOB) Beobachtungen.\n\n::: {.callout-caution collapse=\"true\"}\n## Warum enthält ein Bootstrap Datensatz nur rund 2/3 der Datenpunkte? (optional)\n\nUnser Trainingsdatensatz enthält $n$ Beobachtungen. Beim Bootstrap ziehen wir genau $n$ Beobachtungen **mit Zurücklegen** (wenn wir ohne Zurücklegen samplen würden, dann würde jedes Mal der ursprüngliche Trainingsdatensatz resultieren).\n\nBei jeder Ziehung hat jede Beobachtung im Trainingsdatensatz eine Wahrscheinlichkeit von $1/n$ um ins Sample zu gelangen. Dementsprechend ist die Wahrscheinlichkeit, dass eine Beobachtung während des Bootstrap nicht gezogen wird $\\left(1 - \\frac{1}{n}\\right)^n$.\n\nDaraus folgt, dass die Wahrscheinlichkeit einer Beobachtung mindestens einmal gezogen zu werden $1 - \\left(1 - \\frac{1}{n}\\right)^n$ ist.\n\nBeispiel: für einen Trainingsdatensatz der Grösse $n=100$, ergibt sich eine Wahrscheinlichkeit, dass eine Beobachtung mindestens einmal gezogen wird, von $1 - \\left(1 - \\frac{1}{100}\\right)^{100}=0.63\\approx 2/3$.\n:::\n\nWarum sind OOB Beobachtungen nützlich? Weil die jeweils rund 1/3 OOB Beobachtungen für eine Art von **Cross-Validation** genutzt werden können. Wir schauen für jede Beobachtung im Trainingsdatensatz, für welchen der $B$ Bäume sie OOB war. Dann verwenden wir diese Bäume, um für die OOB Beobachtung Vorhersagen zu rechnen. Die resultierenden Vorhersagen werden aggregiert. Wenn wir dies für jede Beobachtung im Trainingsdatensatz machen, dann kriegen wir für jede Beobachtung eine Vorhersage von Bäumen, für welche diese Beobachtung nicht im Training verwendet wurde.\n\nFür grosse Trainingsdatensätze kann das ein sehr wertvolles Vorgehen sein, weil K-Fold Cross-Validation in diesen Fällen sehr \"teuer\" ist (`R` läuft sehr lange!).\n\n### Variable Importance\n\nWir bewegen uns hier nun immer stärker in Richtung **Black-Box** Modelle. Darum wird das Thema **Variable Importance** (VIP) nun wichtig. Das heisst, wir müssen uns nun verstärkt überlegen, wie wir aus dem Modell lernen können, welche Input-Variablen im Modell wichtig sind.\n\nBeim linearen und logistischen Regressionsmodell war das relativ einfach, da man die Wichtigkeit einer Input-Variable sehr gut anhand des dazugehörigen Modellparameters abschätzen kann. Auch bei Entscheidungsbäumen ist es simpel: Variablen, welche in Splits weiter oben im Baum verwendet werden, sind tendenziell wichtiger als Variablen, die in Splits weiter unten vorkommen und garantiert wichtiger als Variablen, die im Baum *nicht* verwendet werden.\n\nDie gute Nachricht ist, dass es auch für Ensembles gute und konzeptionell einfache Methoden gibt. Bagging ist ja bekanntlich ein Modell, das über $B$ Entscheidungsbäume aggregiert. Wenn wir beispielsweise die Wichtigkeit für die Input-Variable $x_{i1}$ messen wollen, dann schauen wir in jedem der $B$ Bäume, wie gross die **Reduktion** im MSE (Regression) bzw. im Gini Index (Klassifikation) ist durch einen Split, in dem die Variable $x_{i1}$ verwendet wurde. Die VIP der Variable $x_{i1}$ ist dann einfach der Durchschnitt über die $B$ gemessenen Reduktionen in der Kostenfunktion (wenn die Variable $x_{i1}$ in einem der Bäume nicht verwendet wird, dann beträgt die Reduktion für diesen Baum 0). \n\nHäufig rechnet man VIP gleich für alle Input-Variablen und **normalisiert** sie, so dass der maximal mögliche Wert von VIP 1 ist. Das erreichen wir, indem wir alle (unnormalisierten) VIP Werte durch den maximalen VIP Wert teilen.\n\nEin Nachteil dieser Methode ist, dass wir daraus die **Richtung des Einflusses** der Input-Variable auf den Output *nicht* ablesen können.\n\n## Random Forests\n\nWir haben in der Einführung gesehen, dass Ensemble Modelle vor allem dann gut funktionieren, wenn die individuellen Bäume möglichst wenig (am liebsten gar nicht) korreliert sind.\n\nBeim Bagging sind die Bäume aber oft sehr stark korreliert. Wenn wir z.B. einen Datensatz mit einer wichtigen Input-Variable haben (z.B. `econage` im `housingrents` Datensatz), dann wird beinahe jeder Baum im Bagging Ensemble im ersten Split `econage` verwenden und dementsprechend werden alle Bäume relativ ähnlich sein.\n\n::: {.callout-note}\n## Unterschied zwischen Random Forests und Bagging\n\nUm mehr Diversität (d.h. weniger Korrelation) unter den Bäumen herzustellen, macht die **Random Forest** Methode einen kleinen, aber cleveren Trick: für jeden individuellen Baum und jeden Split stehen nur $m$ **zufällig** ausgewählte Input-Variablen zur Verfügung (wobei $m$ kleiner ist als die Anzahl Input-Variablen $p$). So ergeben sich vielfältigere Bäume, wodurch die Reduktion der Varianz im Ensemble grösser wird.\n\nAbgesehen davon, funktionieren Random Forests aber sonst genau gleich wie Bagging.\n:::\n\nWas heisst das konkret für das `housingrents` Beispiel? Die dominante Variable `econage` steht so nicht für jeden ersten Split zur Verfügung und so zwingen wir die Bäume zu mehr Diversität.\n\n$m$ ist der wichtigste Hyperparameter von Random Forest Modellen, weshalb wir den optimalen Wert für $m$ typischwerweise mittels Hyperparameter Tuning suchen. Wenn die Trainingsdaten jedoch gross sind, dann kann ein solches Tuning allerdings lange dauern. In der Praxis hat sich darum $m=\\sqrt{p}$ als guter Wert herausgestellt. Wenn wir also kein Hyperparameter-Tuning machen wollen, dann kann $m$ manuell auf $\\sqrt{p}$ gesetzt werden. Die Anzahl Bäume $B$ kann problemlos auf einen grossen Wert gesetzt werden (z.B. $B=10'000$). Hierbei besteht keine Gefahr für Overfitting. Warum nicht? Der Hyperparameter $B$ kann hier wie die Grösse einer Stichprobe angeschaut werden und aus der klassischen Statistik wissen wir, dass unsere Schätzer mit grösseren Stichproben genauer und besser werden (und nie schlechter).\n\nDie Tatsache, dass ein Random Forest in vielen Fällen auch ohne Hyperparameter Tuning gute Resultate liefert, ist übrigens einer der Hauptgründe, warum dieses Modell in der Praxis so beliebt ist.\n\nEin Nachteil von Random Forests ist, dass die Trainingsphase länger dauern kann, insbesondere wenn wir uns entscheiden, gewisse Hyperparameter doch zu tunen. Wenn wir z.B. $B=10'000$ setzen, dann heisst das, dass wir für jeden Hyperparameter Wert 10'000 Entscheidungsbäume schätzen müssen. Doch auch hier gibt es eine offensichtliche Lösung, denn die einzelnen Bäume werden unabhängig voneinander trainiert und darum ist es sehr einfach den Rechenprozess zu **parallelisieren** (z.B. auf mehrere Cores Ihres Computers).\n\n#### Frage {.unnumbered}\n\nSie haben einen Datensatz und trainieren 3 Modelle: einen einfachen Klassifikationsbaum, ein Bagging Modell sowie einen Random Forest. Was erwarten Sie a-priori bezüglich der Performance dieser drei Modelle? ('>' bedeutet 'besser als')\n\n* Klassifikationsbaum > Bagging > Random Forest\n* Random Forest > Bagging > Klassifikationsbaum\n* Bagging > Random Forest > Klassifikationsbaum\n* Random Forest > Klassifikationsbaum > Bagging\n\n::: {.callout-tip collapse=\"true\"}\n## Lösung\n\nDie korrekte Antwort ist: Random Forest > Bagging > Klassifikationsbaum.\n\nJedes Ensemble sollte den einzelnen Klassifikationsbaum klar outperformen. Random Forests sollten zudem durch die höhere Diversität der einzelnen Bäume besser performen als Bagging.\n:::\n\n## Boosting\n\nWir haben gesehen, dass beim Bagging und bei Random Forests eine grosse Anzahl Entscheidungsbäume gefittet werden, die dann zusammen das Ensemble ergeben. Dabei wurden die Bäume **unabhängig** voneinander gefittet, wodurch das Modell-Training gut parallelisiert werden konnte.\n\nAuch beim Boosting geht es darum, die Vorhersagen von vielen verschiedenen (kleinen) Entscheidungsbäumen zu kombinieren. Jedoch findet beim Boosting das Modell-Fitting bzw. das Training des Modells **sequenziell** statt. Der erste Baum wird auf dem vollen Trainingsdatensatz gefittet. Der zweite Baum versucht dann die Fehler des ersten Baums auszumerzen. Der dritte Baum versucht dann die Fehler des ersten und zweiten Baums auszumerzen, usw. So entsteht ein **iterativer** Trainingsprozess, in dem sich der $b$-te Baum darauf fokussiert die Fehler der $b-1$ vorherigen Bäume zu korrigieren.\n\nWeil beim Boosting die Bäume sequenziell gefittet werden, ist das Training nicht mehr so einfach parallelisierbar. Deshalb ist dieser Algorithmus im Training tendenziell etwas langsamer als beispielsweise Random Forests. Oft führen Boosting Modelle aber zu den besten Vorhersagen in Praxisprojekten!\n\nEs gibt viele verschiedene Boosting Algorithmen und Modelle. Wir werden uns hier auf den **Gradient Boosting** Algorithmus konzentrieren, da dieser Algorithmus in der Praxis am häufigsten verwendet wird. Ein weiterer bekannter Boosting Algorithmus ist **AdaBoost**, bei dem falsch klassifizierte Beobachtungen im Fitting des nächsten Baums ein höheres Gewicht im Training erhalten.\n\n### Modelltraining\n\nWir schauen uns hier der Einfachheit halber an, wie der Gradient Boosting Lernalgorithmus für das **Regressionsproblem** funktioniert. Der Algorithmus für das Klassifikationsproblem ist ähnlich, aber technisch etwas komplexer.\n\nDer **Lernalgorithmus** funktioniert wie folgt [@islr, Kapitel 8]:\n\n1. Wir initialisieren das Boosting Modell mit $\\hat{f}(\\mathbf{x}_i) = 0$ und wir initialisieren die **Residuen** $r_i$ mit den Werten der Outputvariable, also $r_i=y_i$ für alle Trainingsbeobachtungen $i = 1,\\dots ,n$.\n2. Danach iterieren wir über $B$ Bäume, also über $b=1,2,\\dots,B$:\n    + Wir fitten den $b$-ten Baum $\\hat{f}_b$ mit insgesamt $d$ Splits so gut wie möglich auf die aktuellen Residuen $r_i$.\n    + Wir updaten das Boosting Modell mit dem im vorherigen Schritt gefitteten Baum, indem wir den neuen Baum wie folgt hinzufügen: $\\hat{f}(\\mathbf{x}_i) := \\hat{f}(\\mathbf{x}_i) + \\lambda \\hat{f}_b(\\mathbf{x}_i)$. Wir fügen also die Vorhersage des neuen Baums zum Modell hinzu, multiplizieren die neuen Vorhersagen aber mit dem **Shrinkage** Faktor $\\lambda$.\n    + Nun berechnen wir die neuen Residuen zwischen den Werten der Zielvariable und den aktuellen Vorhersagen des Boosting Modells für alle Trainingsbeobachtungen: $r_i := y_i - \\hat{f}(\\mathbf{x}_i)$.\n3. Nachdem wir über alle $B$ Bäume iteriert haben, kriegen wir unser finales Boosting Modell, nämlich $\\hat{f}(\\mathbf{x}_i) = \\sum_{b=1}^B \\lambda \\hat{f}_b(\\mathbf{x}_i)$.\n\nAus obigem Algorithmus ist ersichtlich, dass Gradient Boosting drei wichtige **Hyperparameter** hat:\n\n* Die Anzahl Bäume $B$, die in das Ensemble einfliessen. Im Gegensatz zu Bagging und Random Forest kann es beim Boosting zu Overfitting kommen, wenn wir eine zu grosse Anzahl Bäume $B$ wählen, denn jeder Baum versucht ja die Fehler aller vorangehenden Bäume zu verbesseren oder korrigieren. Irgendwann kommen wir so in den Bereich, wo der Algorithmus nur noch den unsystematischen Teil der Information (**Noise**) zu fitten versucht.\n* Der Hyperparameter $d$ bezeichnet die Anzahl Splits, die wir in den einzelnen Bäumen zulassen. Erstaunlich oft funktionieren Bäume mit einem Split, also $d=1$, gut in der Praxis. In diesem Fall handelt es sich um sogenannte Entscheidungsstümmel (engl. *Decision Stumps*).\n* Der dritte wichtige Hyperparameter ist der Shrinkage Hyperparameter $\\lambda \\leq 1$. Wir wollen damit sicherstellen, dass das Boosting Ensemble nicht zu schnell lernt. Es hat sich in der Praxis herausgestellt, dass langsam lernende Boosting Ensembles zu einem besseren Ensemble führen. Der Shrinkage Hyperparameter kann auch als eine Form von **Regularisierung** interpretiert werden.\n\n<!-- In diesem Fall fitten wir effektiv ein *additives Modell* (warum?). -->\n\n<!-- <div style = \"background-color:#fef9e7; padding:10px\"> -->\n<!-- ```{r, echo=FALSE} -->\n<!-- fluidPage( -->\n\n<!--   fluidRow( -->\n<!--     withMathJax(), -->\n<!--     p(\"In dieser Demo verwenden wir die Gradient Boosting Methode auf einem simplen  -->\n<!--       Datensatz mit einer Input-Variable. Wir schauen uns an, wie sich die  -->\n<!--       Hyperparameter dieser Methode (B, Shrinkage, Anzahl Splits) auf den Fit an -->\n<!--       die Trainingsdaten sowie die Fehler auf Training- und Testdatensatz auswirken.  -->\n<!--       Abgebildet ist immer nur der Trainingsdatensatz. Der Testdatensatz hat immer die -->\n<!--       selbe Grösse wie der Trainingsdatensatz.\") -->\n<!--   ), -->\n\n<!--   fluidRow( -->\n<!--     column(width = 4, numericInput(\"n_boosting\", \"Anzahl Beobachtungen\", 50, 1, 200, 10)) -->\n<!--   ), -->\n\n<!--   fluidRow( -->\n<!--     column(width = 4, numericInput(\"B\", \"Anzahl Bäume B\", 1, 1, 500, 10)), -->\n<!--     column(width = 4, numericInput(\"shrinkage\", \"Shrinkage\", 1, 0.01, 1, 0.01)), -->\n<!--     column(width = 4, numericInput(\"splits\", \"Anzahl Splits\", 1, 1, 5, 1)), -->\n<!--   ), -->\n\n<!--   fluidRow( -->\n<!--     column(width = 12, plotOutput(\"boosting\")) -->\n<!--   ) -->\n<!-- ) -->\n<!-- ``` -->\n<!-- </div><br> -->\n\n<!-- ```{r, context = \"server\"} -->\n<!-- output$boosting <- renderPlot({ -->\n\n<!--   library(gbm) -->\n\n<!--   # Setze den Seed für Reprodzierbarkeit -->\n<!--   set.seed(123) -->\n<!--   # Generiere Daten -->\n<!--   xtrain <- runif(input$n_boosting, 0, 1) -->\n<!--   ytrain <- 4 * (xtrain-0.5)^2 + rnorm(input$n_boosting, 0, 0.1) -->\n<!--   xtest <- runif(input$n_boosting, 0, 1) -->\n<!--   ytest <- 4 * (xtest-0.5)^2 + rnorm(input$n_boosting, 0, 0.1) -->\n<!--   # Kreiere Data Frames -->\n<!--   train <- data.frame(y = ytrain, x = xtrain) -->\n<!--   test <- data.frame(y = ytest, x = xtest) -->\n<!--   # Rechne Regressionsbaum -->\n<!--   model <- reg_boost <- gbm(y ~ x, data = train, distribution = \"gaussian\",  -->\n<!--                             n.trees = input$B, interaction.depth = input$splits,  -->\n<!--                             shrinkage = input$shrinkage, n.minobsinnode = 1, bag.fraction = 1) -->\n<!--   # Data Frame für Zeichnen der Kurven -->\n<!--   new <- data.frame(x = seq(0, 1, 0.001)) -->\n<!--   # Vorhersagen -->\n<!--   pred_curves <- predict(model, new, n.trees = input$B) -->\n<!--   pred_train <- predict(model, train, n.trees = input$B) -->\n<!--   pred_test <- predict(model, test, n.trees = input$B) -->\n<!--   # 2 Plots nebeneinander -->\n<!--   par(mfrow = c(1,2)) -->\n<!--   par(bg = \"#fef9e7\") -->\n<!--   # Streuudiagramm -->\n<!--   plot(xtrain, ytrain, col = \"blue\", pch = 16) -->\n<!--   # Kurve Modell -->\n<!--   lines(seq(0, 1, 0.001), pred_curves, type = \"l\", col = \"red\", lwd = 2) -->\n<!--   # RMSE Train/Test -->\n<!--   rmse_train <- sqrt(mean((ytrain - pred_train)^2)) -->\n<!--   rmse_test <- sqrt(mean((ytest - pred_test)^2)) -->\n<!--   # Barplot RMSE -->\n<!--   barplot(c(rmse_train, rmse_test), main = \"Root Mean Squared Error (RMSE)\",  -->\n<!--           ylim = c(0, 1), names.arg = c(\"Train\", \"Test\")) -->\n<!--   # RMSE als Text -->\n<!--   text(c(0.7,1.9), y=0.5, labels = c(round(rmse_train, 2), round(rmse_test, 2))) -->\n\n<!-- }) -->\n<!-- ``` -->\n\n\n<!-- <div style = \"background-color:#fef9e7; padding:10px\"> -->\n<!-- ```{r, \"boostingOverfitting\", echo = FALSE} -->\n<!-- question(\"Sie haben ein Gradient Boosting Modell verwendet, aber es hat leider zu Overfitting geführt. Welche Möglichkeiten haben Sie, um das Problem des Overfittings beim Boosting zu beheben?\", -->\n<!--   answer(\"Wir senken $\\\\lambda$ und machen den Lernprozess so langsamer.\", correct = TRUE), -->\n<!--   answer(\"Wir erhöhen die Anzahl Bäume $B$, die trainiert werden sollen.\", correct = FALSE), -->\n<!--   answer(\"Early Stopping: wir lernen nur so lange neue Bäume bis der Fehler auf dem Validierungsdatensatz nicht mehr runter geht.\", correct = TRUE), -->\n<!--   answer(\"Wir reduzieren die Komplexität der einzelnen Bäume, indem wir $d$ reduzieren.\", correct = TRUE), -->\n<!--   correct = \"Richtig!\", -->\n<!--   incorrect = \"Falsch!\", -->\n<!--   allow_retry = TRUE, -->\n<!--   random_answer_order = TRUE -->\n<!-- ) -->\n<!-- ``` -->\n<!-- </div><br> -->\n\nWir werden später im zweiten Teil des Buchs den **Gradient Descent** Algorithmus kennen lernen. In der folgenden optionalen Box lernen Sie, inwiefern Gradient Boosting mit Gradienten und Ableitungen zu tun hat.\n\n::: {.callout-caution collapse=\"true\"}\n## Was hat der Gradient Boosting Algorithmus mit Gradient Descent zu tun? (optional)\n\nSie werden den **Gradient Descent** Algorithmus später kennenlernen. Der **Gradient Boosting** Algorithmus funktioniert (wie es der Name bereits verrät) ähnlich. Doch es ist vielleicht nicht ganz so offensichtlich, warum das so ist. Schauen wir es uns zusammen an!\n\nBeim Regressionsproblem versuchen wir in den meisten Fällen den **Mean Squared Error** (MSE) als Kostenfunktion zu minimieren. Für eine einzelne Trainingsbeobachtung $i$ können die Kosten wie folgt aufgeschrieben werden:\n\n$$\nJ_i(y_i, \\hat{f}(\\mathbf{x}_i)) = \\frac{1}{2}\\left(y_i - \\hat{f}(\\mathbf{x}_i)\\right)^2\n$$ \nDie Gesamtkostenfunktion ist dementsprechend die Summe über die individuellen Kosten aller Trainingsbeobachtungen. (Das Dividieren durch $n$ lassen wir hier bewusst weg, da es für die Optimierung nicht relevant ist.)\n\n$$\nJ = \\sum_{i = 1}^n J_i(y_i, \\hat{f}(\\mathbf{x}_i))\n$$\nWir möchten nun unser Boosting Modell $\\hat{f}(\\mathbf{x}_i)$ so verbessern, dass die Kosten reduziert werden. Dazu rechnen wir die Ableitung unserer Gesamtkosten nach $\\hat{f}(\\mathbf{x}_i)$ (also dem Funktionswert für die $i$-te Beobachtung):\n\n$$\n\\begin{split}\n\\frac{\\partial J}{\\partial \\hat{f}(\\mathbf{x}_i)} &= \\frac{\\partial \\sum_i J_i(y_i, \\hat{f}(\\mathbf{x}_i))}{\\partial \\hat{f}(\\mathbf{x}_i)}\\\\ &= \\frac{\\partial J_i(y_i, \\hat{f}(\\mathbf{x}_i))}{\\partial \\hat{f}(\\mathbf{x}_i)}\\\\ &= \\frac{2}{2}\\left(y_i - \\hat{f}(\\mathbf{x}_i)\\right)^{2-1}\\cdot (-1)\\\\ &= -\\left(y_i - \\hat{f}(\\mathbf{x}_i)\\right)\n\\end{split}\n$$\n\nWir sehen also, dass die Ableitung (oder eben der **Gradient**) nichts anderes als das negative **Residuum** ist.\n\nIm zweiten Schritt des Gradient Boosting Algorithmus haben wir gesehen, dass wir einen neuen Baum jeweils wie folgt zum Ensemble hinzufügen:\n\n$$\n\\hat{f}(\\mathbf{x}_i) := \\hat{f}(\\mathbf{x}_i) + \\lambda \\hat{f}_b(\\mathbf{x}_i)\n$$\n\nWie im Algorithmus beschrieben wird der neue Baum jeweils so gut wie möglich auf die aktuellen Residuen gefittet. Wir können also den neuen Baum $\\hat{f}_b(\\mathbf{x}_i)$ als eine **Annäherung an die Residuen** (den negativen Gradient) interpretieren. In anderen Worten: der neue Baum versucht die Residuen so gut wie möglich zu beschreiben. So können wir die Update-Gleichung umschreiben als:\n\n$$\n\\begin{split}\n\\hat{f}(\\mathbf{x}_i) &:= \\hat{f}(\\mathbf{x}_i) + \\lambda \\cdot (y_i - \\hat{f}(\\mathbf{x}_i))\\\\\n&:= \\hat{f}(\\mathbf{x}_i) - \\lambda \\cdot \\frac{\\partial J_i(y_i, \\hat{f}(\\mathbf{x}_i))}{\\partial \\hat{f}(\\mathbf{x}_i)}\n\\end{split}\n$$\n\nSpäter, wenn wir den Gradient Descent kennen lernen, werden Sie diesen letzten Ausdruck als eine Art von Gradient Descent erkennen.\n\nQuelle: [Cheng Li, A Gentle Introduction to Gradient Boosting](http://www.chengli.io/tutorials/gradient_boosting.pdf)\n:::\n\n## Ensembles in R\n\nZur Illustration der Ensembles in `R` verwenden wir auch hier den **Heart** Datensatz, den wir bereits in @sec-tree verwendet haben.\n\n\n::: {.cell}\n\n:::\n\n\nWir laden als erstes diverse R-Packages. Die Daten sind hier bereits geladen als `heart`. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(vip)\nlibrary(gbm)\nlibrary(ranger)\nlibrary(xgboost)\nlibrary(tidyverse)\nlibrary(tidymodels)\nlibrary(randomForest)\n```\n:::\n\n\nIm Vergleich zu @sec-tree entfernen wir die Beobachtungen mit fehlenden Werten in mindestens einer Spalte, weil die Modelle, die wir später anschauen werden, nicht gut mit fehlenden Werten umgehen können. Darum enthält der heart Dataframe nur noch 297 Zeilen.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Entferne alle Zeilen mit fehlenden Werten.\nheart <- na.omit(heart)\n\n# Wie viele Zeilen bleiben übrig?\nnrow(heart)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 297\n```\n\n\n:::\n:::\n\n\nWir machen hier nun einen Train-Test Split, weil wir dann später alle Modelle auf einem Testdatensatz evaluieren wollen. Wir bilden auch schon gleich die 5 Folds für die Cross-Validation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Seed, um den Train-Test Split reproduzierbar zu machen\nset.seed(123)\n\n# Split (75% Training, 25% Test)\ntrain_test_split <- initial_split(heart, prop = 3/4, strata = hd)\n\ntrain <- training(train_test_split)\ntest  <- testing(train_test_split)\n\n# Seed, um 5-Fold Cross-Validation reproduzierbar zu machen\nset.seed(456)\n\n# 5-Fold CV\nfolds <- vfold_cv(train, v = 5, repeats = 1, strata = hd)\n```\n:::\n\n\n### Bagging\n\nWie oben schon etwas angetönt, ist es beim Bagging nicht zwingend nötig irgendwelche Hyperparameter zu tunen. Die Anzahl Bäume $B$ sollte einfach hoch genug gewählt werden und die individuellen Bäume müssen nicht beschränkt werden. Aus diesem Grund werden wir hier nicht `tidymodels` verwenden (wir sparen uns hier den ganzen Overhead von `tidymodels`). Stattdessen verwenden wir das `R` Package `randomForest`. Sie werden später sehen, dass wir dasselbe Package auch für die Random Forest Methode verwenden werden (wie es der Name natürlich bereits verrät).\n\nWir übergeben der `randomForest()` Funktion als erstes die Modellformel `hd ~ .` und den Trainingsdatensatz. Das Argument `mtry` wird vor allem bei den Random Forest Modellen wichtig sein. Es gibt der Funktion vor, wie viele der Input-Variablen an jedem Split eines individuellen Baums als mögliche Splitvariablen zur Verfügung stehen. Hier, beim Bagging, sollen bei jedem Split **alle Input-Variablen** zur Verfügung stehen. Darum setzen wir das Argument auf `ncol(train) - 1` (= 13), die Anzahl Input-Variablen. Das Argument `ntree = 10000` gibt der Funktion vor, dass wir $B=10'000$ Bäume schätzen wollen. Zum Schluss sagen wir noch, dass wir VIP auch gleich messen wollen.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Seed für Reproduzierbarkeit (Bagging basiert stark auf SAMPLING)\nset.seed(44)\n\n# Fitting eines Bagging Modells\nbag_fit <- \n  randomForest(hd ~ ., \n               data = train, \n               mtry = ncol(train) - 1, \n               ntree = 10000, \n               importance = TRUE)\n\n# Output des Modells\nbag_fit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\n randomForest(formula = hd ~ ., data = train, mtry = ncol(train) -      1, ntree = 10000, importance = TRUE) \n               Type of random forest: classification\n                     Number of trees: 10000\nNo. of variables tried at each split: 13\n\n        OOB estimate of  error rate: 22.97%\nConfusion matrix:\n    no yes class.error\nno  97  23   0.1916667\nyes 28  74   0.2745098\n```\n\n\n:::\n:::\n\n\nSie sehen oben eine Zusammenfassung des Fit-Objekts. Insbesondere interessant ist die **Out-of-Bag (OOB) Error Rate**, die hier 22.97% beträgt. Die Error Rate ist das Gegenstück zur Accuracy: Error Rate = 1 - Accuracy.\n\nSelbstverständlich könnten wir das gefittete Modell nun bereits verwenden, um harte oder weiche Vorhersagen zu machen, z.B. für die erste Trainingsbeobachtung:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Vorhersagen machen\npredict(bag_fit, newdata = train[1, ], type = \"prob\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n      no    yes\n1 0.9845 0.0155\nattr(,\"class\")\n[1] \"matrix\" \"array\"  \"votes\" \n```\n\n\n:::\n\n```{.r .cell-code}\npredict(bag_fit, newdata = train[1, ], type = \"class\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n 1 \nno \nLevels: no yes\n```\n\n\n:::\n:::\n\n\n**Wichtig:** die `predict()` Funktion in obigem Code Block ist aus Base `R`. Bei der `predict()` Funktion aus `tidymodels` würde das Argument `newdata` anders heissen, nämlich `new_data`.\n\nZum Schluss können wir uns noch die Variable Importance anschauen:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Variable Importance\nrandomForest::importance(bag_fit, type = 2)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         MeanDecreaseGini\nage             7.8986270\nsex             1.5685783\ncp             13.5563437\ntrestbps        8.6907289\nchol            7.6470803\nfbs             0.3817802\nrestecg         1.7126149\nthalach        12.2312568\nexang           1.8729007\noldpeak        15.3368627\nslope           3.0001435\nca             12.4442411\nthal           23.4377673\n```\n\n\n:::\n:::\n\n\nWir sehen, dass die Variable `thal` klar zur stärksten durchschnittlichen Reduktion im Gini Index führt!\n\n### Random Forests\n\nWir schauen uns hier zuerst an, wie man Random Forests ohne `tidymodels` rechnen kann. Dazu verwenden wir wie bereits beim Bagging die `randomForest()` Funktion. Der einzige Unterschied im Vergleich zum Bagging ist, dass wir nun für das Argument `mtry` einen Wert kleiner als die Anzahl Input-Variablen setzten. Wie oben erwähnt gilt die Faustregel, dass $m=\\sqrt{p}=\\sqrt{13}=3.61$. Darum setzten wir `mtry = 4`. Nun stehen bei jedem Split in jedem individuellen Baum nur **vier zufällig ausgewählte Input-Variablen** zur Verfügung. Wie gesagt: ein kleiner, aber feiner Trick!\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Seed für Reproduzierbarkeit\nset.seed(22)\n\n# Fitting eines Random Forest Modells\nrf_fit <- \n  randomForest(hd ~ ., \n               data = train, \n               mtry = 4, \n               ntree = 10000, \n               importance = TRUE)\n\n# Output des Modells\nrf_fit\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\n randomForest(formula = hd ~ ., data = train, mtry = 4, ntree = 10000,      importance = TRUE) \n               Type of random forest: classification\n                     Number of trees: 10000\nNo. of variables tried at each split: 4\n\n        OOB estimate of  error rate: 19.37%\nConfusion matrix:\n     no yes class.error\nno  103  17   0.1416667\nyes  26  76   0.2549020\n```\n\n\n:::\n:::\n\n\nWir sehen, dass die OOB Error Rate nun nur 19.37% beträgt. Wir dürfen also erwarten, dass der Random Forest bessere Vorhersagen machen wird als Bagging.\n\nNun fitten wir den Random Forest mit `tidymodels` und der `ranger` Engine. Schauen Sie sich folgenden Code genau an. Viele Elemente kennen Sie bereits. Was ist neu? Wir verwenden das `R` Package `doParallel`, um das Tuning zu parallelisieren. Das heisst, jede Hyperparameter Kombination wird auf einem anderen Core Ihres Computers gerechnet. So verläuft der Trainingsprozess relativ schnell! Mit `grid = 30` lassen wir einfach 30 Hyperparamter Kombinationen testen; wir geben sie hier ausnahmsweise nicht explizit vor. Dadurch erstellt `tidymodels` automatisch ein **Space-filling Design**. Doch was bedeutet das? Aus allen möglichen Kombinationen von Werten für `min_n` (minimale Anzahl Beobachtungen in einem Node eines einzelnen Baums) sowie `mtry` ($m$) wählt `tidymodels` automatisch 30 Kombinationen, die Sinn machen und die den Raum (*Space*), welcher durch die zwei Hyperparameter aufgespannt wird, möglichst gut ausfüllen (*Space-filling*).\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Spezifikation des RFs\nrf_mod <- \n  rand_forest(mtry = tune(), min_n = tune(), trees = 1000) |> \n  set_engine(\"ranger\") |> \n  set_mode(\"classification\")\n\n# Workflow\nrf_workflow <- \n  workflow() |>  \n  add_model(rf_mod) |> \n  add_formula(hd ~ .)\n\n# Parallel Processing\ndoParallel::registerDoParallel()\n\n# Seed für Reproduzierbarkeit\nset.seed(22)\n\n# Model Fitting / Tuning\nrf_res <- \n  rf_workflow |> \n  tune_grid(folds,\n            grid = 30,\n            control = control_grid(save_pred = TRUE, save_workflow = TRUE),\n            metrics = metric_set(roc_auc))\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\ni Creating pre-processing data to finalize 1 unknown parameter: \"mtry\"\n```\n\n\n:::\n\n```{.r .cell-code}\n# Wir sortieren die Hyperparameter Spezifikationen nach ROC AUC\nrf_res |> \n  show_best(metric = \"roc_auc\", n = 10) |> \n  arrange(desc(mean))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 10 × 8\n    mtry min_n .metric .estimator  mean     n std_err .config         \n   <int> <int> <chr>   <chr>      <dbl> <int>   <dbl> <chr>           \n 1     1    12 roc_auc binary     0.910     5  0.0279 pre0_mod01_post0\n 2     1    33 roc_auc binary     0.907     5  0.0289 pre0_mod03_post0\n 3     1    20 roc_auc binary     0.906     5  0.0288 pre0_mod02_post0\n 4     2    38 roc_auc binary     0.903     5  0.0315 pre0_mod06_post0\n 5     2     5 roc_auc binary     0.902     5  0.0285 pre0_mod04_post0\n 6     2    25 roc_auc binary     0.901     5  0.0297 pre0_mod05_post0\n 7     3    17 roc_auc binary     0.898     5  0.0271 pre0_mod08_post0\n 8     3     9 roc_auc binary     0.896     5  0.0264 pre0_mod07_post0\n 9     3    32 roc_auc binary     0.895     5  0.0289 pre0_mod09_post0\n10     5    16 roc_auc binary     0.894     5  0.0283 pre0_mod13_post0\n```\n\n\n:::\n:::\n\n\nInteressanterweise ist für `mtry` der Wert 1 optimal. Das heisst für jeden Split steht nur eine zufällig ausgewählte Input-Variable zur Verfügung. Wir können die Tuning Resultate auch grafisch darstellen:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Plot Tuning Resultate\nautoplot(rf_res)\n```\n\n::: {.cell-output-display}\n![](06_ensemble_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n\nWährend das Muster für `mtry` links klar ist (je grösser `mtry`, desto schlechter ROC AUC), gibt es für `min_n` (rechts) kein klar erkennbares Muster.\n\nNun rechnen wir den Last Fit auf dem ganzen Trainingsdatensatz und mit optimalen Hyperparameterwerten. Mit `importance = \"impurity\"` sagen wir der Funktion, dass wir die VIP Werte auch gleich mitrechnen wollen.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Last Fit Spezifikation (optimale Hyperparameter Werte)\nlast_rf_mod <-\n  rand_forest(mtry = 1, min_n = 12, trees = 1000) |> \n  set_mode(\"classification\") |> \n  set_engine(\"ranger\", importance = \"impurity\")\n\n# Workflow anpassen (optimales Modell)\nlast_rf_workflow <- \n  rf_workflow |> \n  update_model(last_rf_mod)\n\n# Last Fit (auf ganzem Trainingsdatensatz)\nlast_rf_fit <-\n  last_rf_workflow |> \n  fit(data = train)\n```\n:::\n\n\nSchauen wir uns kurz das gefittete Objekt an:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Modell Output\nlast_rf_fit |> \n  extract_fit_parsnip()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nparsnip model object\n\nRanger result\n\nCall:\n ranger::ranger(x = maybe_data_frame(x), y = y, mtry = min_cols(~1,      x), num.trees = ~1000, min.node.size = min_rows(~12, x),      importance = ~\"impurity\", num.threads = 1, verbose = FALSE,      seed = sample.int(10^5, 1), probability = TRUE) \n\nType:                             Probability estimation \nNumber of trees:                  1000 \nSample size:                      222 \nNumber of independent variables:  13 \nMtry:                             1 \nTarget node size:                 12 \nVariable importance mode:         impurity \nSplitrule:                        gini \nOOB prediction error (Brier s.):  0.1399315 \n```\n\n\n:::\n:::\n\n\nAuch hier sehen wir den OOB Fehler. Er liegt bei knapp 14%. Hier handelt es sich jedoch um das sogenannte **Brier Score**, weshalb dieser Wert nicht direkt mit den vorherigen OOB Werten verglichen werden kann. Wir können die VIP Werte für die Input-Variablen plotten mit der Funktion `vip()`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Variable Importance Plot\nlast_rf_fit |> \n  extract_fit_parsnip() |>  \n  vip(num_features = 13)\n```\n\n::: {.cell-output-display}\n![](06_ensemble_files/figure-html/unnamed-chunk-14-1.png){width=672}\n:::\n:::\n\n\nDie Variable `thal` geht auch hier als die wichtigste Variable hervor.\n\n### Gradient Boosting\n\nWir fitten hier den Gradient Boosting Algorithmus in einem ersten Schritt mit dem traditionellen `gbm` Package. Dieses Package erwartet, dass die kategorische Zielvariable 0/1 kodiert ist, weshalb ich in einem ersten Schritt eine Umkodierung vornehme.\n\nDanach fitten wir mit der Funktion `gbm()` das Modell. In der Modellformel entferne ich die ursprüngliche Zielvariable `hd`. Mit `distribution = \"bernoulli\"` sagen wir der Funktion, dass es sich um ein binäres Klassifikationsproblem handelt. Die drei wichtigen Hyperparameter heissen hier etwas anders:\n\n* $B$ &rarr; `n.trees`\n* $d$ &rarr; `interaction.depth`\n* $\\lambda$ &rarr; `shrinkage`\n\nSie sehen, dass wir via dem Argument `cv.folds = 5` auch eine interne Cross-Validation betreiben. Wir wollen damit herausfinden, wie viele Trees nötig sind und ob es allenfalls weniger Bäume als `n.trees = 10000` braucht.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Seed für Reproduzierbarkeit\nset.seed(15)\n\n# Wir müssen Zielvariable in 0/1 umkodieren für gbm Package\ntrain$y <- as.integer(train$hd) - 1\n\n# Fitting eines GBM Modells\ngbm_fit <- gbm(\n  formula = y ~ . - hd,\n  distribution = \"bernoulli\",\n  data = train,\n  n.trees = 10000,\n  interaction.depth = 1,\n  shrinkage = 0.001,\n  cv.folds = 5,\n  n.cores = NULL,\n  verbose = FALSE\n)\n\n# Output\nprint(gbm_fit)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngbm(formula = y ~ . - hd, distribution = \"bernoulli\", data = train, \n    n.trees = 10000, interaction.depth = 1, shrinkage = 0.001, \n    cv.folds = 5, verbose = FALSE, n.cores = NULL)\nA gradient boosted model with bernoulli loss function.\n10000 iterations were performed.\nThe best cross-validation iteration was 7362.\nThere were 13 predictors of which 13 had non-zero influence.\n```\n\n\n:::\n:::\n\n\nHa, tatsächlich ist die optimale Anzahl Bäume (also das optimale $B$) tiefer als 10'000 und liegt bei 7'362 Bäumen. Der Cross-Validation Fehler ist bei dieser optimalen Anzahl Bäume am tiefsten. Dieses Resultat kann man sich auch noch grafisch ausgeben lassen:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Kostenfunktion für steigende Anzahl Trees\ngbm.perf(gbm_fit, method = \"cv\")\n```\n\n::: {.cell-output-display}\n![](06_ensemble_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 7362\n```\n\n\n:::\n:::\n\n\nSie sehen, dass wir nach der blau gestrichelten Vertikalen in den Overfitting Bereich kommen: die Kosten auf dem Trainingsdatensatz (in schwarz) gehen weiter runter, aber die Kosten auf den CV Folds beginnen wieder leicht zu steigen (in anderen Worten: die Varianz des Modells beginnt zu steigen).\n\nWir fitten nun also das finale Gradient Boosting Modell mit der optimalen Anzahl Bäume. Die anderen Hyperparameter tunen wir hier der Einfachheit halber nicht. Mithilfe des Packages `vip` lassen wir uns die Wichtigkeit der verschiedenen Variablen visualisieren.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Finales GBM Modell\ngbm_final_fit <- gbm(\n  formula = y ~ . - hd,\n  distribution = \"bernoulli\",\n  data = train,\n  n.trees = 7362,\n  interaction.depth = 1,\n  shrinkage = 0.001,\n  n.cores = NULL,\n  verbose = FALSE\n)\n\n# Variable Importance\nvip(gbm_final_fit)\n```\n\n::: {.cell-output-display}\n![](06_ensemble_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n:::\n\n\nWie Sie wohl bereits vermuten, ist auch hier die Variable `thal` am wichtigsten.\n\n### Performance auf Testdaten\n\n\n::: {.cell}\n\n:::\n\n\nNun vergleichen wir die insgesamt 5 Modelle auf dem Testdatensatz. Neben Bagging, zwei Random Forest Modellen (einmal gefittet mit `randomForest` und einmal mit `tidymodels` bzw. `ranger`) und Gradient Boosting habe ich hier nochmal einen einfachen Klassifikationsbaum (`last_dt_fit`) aus @sec-tree auf dem Trainingsdatensatz gefittet.\n\nBevor wir uns aber die Resultate auf dem Testdatensatz anschauen, können wir uns für die zwei mit `tidymodels` gefitteten Modelle (Random Forest und Klassifikationsbaum), die ROC Kurven basierend auf den Cross-Validation Resultaten für das jeweils beste Modell anzeigen lassen.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Bestes Modell\nrf_best <- \n  rf_res |> \n  select_best(metric = \"roc_auc\")\n\n# Resultate vorbereiten für ROC Kurve\nrf_auc <- \n  rf_res |> \n  collect_predictions(parameters = rf_best) |> \n  roc_curve(hd, .pred_yes, event_level = \"second\") |> \n  mutate(Modell = \"Random Forest\")\n\n# ROC Kurven vergleichen\nbind_rows(rf_auc, dt_auc) |> \n  ggplot(aes(x = 1 - specificity, y = sensitivity, col = Modell)) + \n  geom_path(linewidth = 1, alpha = 0.8) +\n  geom_abline(lty = 3) + \n  coord_equal() + \n  scale_color_viridis_d(option = \"plasma\", end = .6) +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](06_ensemble_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n:::\n\n\nBasierend auf dieser Visualisierung kann bereits klar gesagt werden, dass ein Ensemble wie das Random Forest Modell einen einzelnen Klassifikationsbaum klar outperformt.\n\nNachfolgend die Resultate auf dem Testset für die beiden Modelle, die mit `tidymodels` gefittet wurden:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Testset-Performance\ntest_dt_aug <- augment(last_dt_fit, test)\ntest_rf_aug <- augment(last_rf_fit, test)\n\n# ROC AUC Klassifikationsbaum\ntest_dt_aug |> \n  roc_auc(truth = hd, .pred_yes, event_level = \"second\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  .metric .estimator .estimate\n  <chr>   <chr>          <dbl>\n1 roc_auc binary         0.832\n```\n\n\n:::\n\n```{.r .cell-code}\n# ROC AUC Random Forest\ntest_rf_aug |> \n  roc_auc(truth = hd, .pred_yes, event_level = \"second\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  .metric .estimator .estimate\n  <chr>   <chr>          <dbl>\n1 roc_auc binary         0.929\n```\n\n\n:::\n\n```{.r .cell-code}\n# ACCURACY Klassifikationsbaum\ntest_dt_aug |> \n  accuracy(truth = hd, .pred_class)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  .metric  .estimator .estimate\n  <chr>    <chr>          <dbl>\n1 accuracy binary         0.773\n```\n\n\n:::\n\n```{.r .cell-code}\n# ACCURACY Random Forest\ntest_rf_aug |> \n  accuracy(truth = hd, .pred_class)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  .metric  .estimator .estimate\n  <chr>    <chr>          <dbl>\n1 accuracy binary         0.907\n```\n\n\n:::\n:::\n\n\nFür die Modelle, die wir nicht mit `tidymodels` gefittet haben, müssen wir leicht anders vorgehen:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Performance der Modelle ohne tidymodels\npred_test_bag <- predict(bag_fit, newdata = test, type = \"prob\")\npred_test_rf <- predict(rf_fit, newdata = test, type = \"prob\")\npred_test_gbm <- predict(gbm_final_fit, n.trees = gbm_final_fit$n.trees, test, type = \"response\")\n\n# Resultate in Data Frame Form\ntest_bag_aug <- data.frame(pred_test_bag) |> \n  bind_cols(hd = test$hd) |> \n  rename(.pred_no = no, .pred_yes = yes) |> \n  mutate(.pred_class = factor(ifelse(.pred_yes >= 0.5, \"yes\", \"no\"), levels = c(\"no\", \"yes\")))\ntest_rfc_aug <- data.frame(pred_test_rf) |> \n  bind_cols(hd = test$hd) |> \n  rename(.pred_no = no, .pred_yes = yes) |> \n  mutate(.pred_class = factor(ifelse(.pred_yes >= 0.5, \"yes\", \"no\"), levels = c(\"no\", \"yes\")))\ntest_gbm_aug <- data.frame(pred_test_gbm) |>\n  bind_cols(hd = test$hd) |>\n  rename(.pred_yes = pred_test_gbm) |>\n  mutate(.pred_no = 1 - .pred_yes,\n         .pred_class = factor(ifelse(.pred_yes >= 0.5, \"yes\", \"no\"), levels = c(\"no\", \"yes\")))\n\n# ROC AUC Bagging\ntest_bag_aug |> \n  roc_auc(truth = hd, .pred_yes, event_level = \"second\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  .metric .estimator .estimate\n  <chr>   <chr>          <dbl>\n1 roc_auc binary         0.904\n```\n\n\n:::\n\n```{.r .cell-code}\n# ROC AUC Random Forest\ntest_rfc_aug |> \n  roc_auc(truth = hd, .pred_yes, event_level = \"second\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  .metric .estimator .estimate\n  <chr>   <chr>          <dbl>\n1 roc_auc binary         0.929\n```\n\n\n:::\n\n```{.r .cell-code}\n# ROC AUC Gradient Boosting\ntest_gbm_aug |>\n  roc_auc(truth = hd, .pred_yes, event_level = \"second\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  .metric .estimator .estimate\n  <chr>   <chr>          <dbl>\n1 roc_auc binary          0.93\n```\n\n\n:::\n\n```{.r .cell-code}\n# ACCURACY Bagging\ntest_bag_aug |> \n  accuracy(hd, .pred_class)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  .metric  .estimator .estimate\n  <chr>    <chr>          <dbl>\n1 accuracy binary         0.813\n```\n\n\n:::\n\n```{.r .cell-code}\n# ACCURACY Random Forest\ntest_rfc_aug |>\n  accuracy(hd, .pred_class)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  .metric  .estimator .estimate\n  <chr>    <chr>          <dbl>\n1 accuracy binary         0.867\n```\n\n\n:::\n\n```{.r .cell-code}\n# ACCURACY Gradient Boosting\ntest_gbm_aug |>\n  accuracy(hd, .pred_class)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# A tibble: 1 × 3\n  .metric  .estimator .estimate\n  <chr>    <chr>          <dbl>\n1 accuracy binary         0.893\n```\n\n\n:::\n:::\n\n\nDie Resultate lassen sich wie folgt zusammenfassen:\n\n| Modell                         | ROC AUC (Testset) | Accuracy (Testset) |\n|--------------------------------|-------------------|--------------------|\n| Klassifikationsbaum (`rpart`)  | 83.2%             | 77.3%              |\n| Bagging (`randomForest`)       | 90.4%             | 81.3%              |\n| Random Forest (`randomForest`) | 92.9%             | 86.7%              |\n| Random Forest (`ranger`)       | 92.9%             | **90.7%**          |\n| Gradient Boosting (`gbm`)      | **93.0%**         | 89.3%              |\n\nWir sehen hier zumindest für das **Heart** Problem eine fantastische Performance von Ensembles im Vergleich zu einfachen Klassifikationsbäumen.\n",
    "supporting": [
      "06_ensemble_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}